import { Category, Product, Coupon } from '@/types';

export const MOCK_CATEGORIES: Category[] = [
  {
    id: 'cat-1',
    name: 'Consumer Electronics',
    slug: 'electronics',
    description: 'Next-gen audio, smart wearables, and premium personal tech',
    imageUrl: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?q=80&w=800&auto=format&fit=crop',
    icon: 'Laptop',
    isFeatured: true,
    sortOrder: 1,
    productCount: 24,
  },
  {
    id: 'cat-2',
    name: 'Luxury Apparel',
    slug: 'apparel',
    description: 'Crafted apparel, tailored ethnic wear, and modern luxury fits',
    imageUrl: 'https://images.unsplash.com/photo-1489987707025-afc232f7ea0f?q=80&w=800&auto=format&fit=crop',
    icon: 'Shirt',
    isFeatured: true,
    sortOrder: 2,
    productCount: 18,
  },
  {
    id: 'cat-3',
    name: 'Home & Living',
    slug: 'home-living',
    description: 'Handcrafted artifacts, minimalist lighting, and luxury decor',
    imageUrl: 'https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?q=80&w=800&auto=format&fit=crop',
    icon: 'Home',
    isFeatured: true,
    sortOrder: 3,
    productCount: 15,
  },
  {
    id: 'cat-4',
    name: 'Timepieces & Jewelry',
    slug: 'watches-jewelry',
    description: 'Precision chronograph watches and heritage handcrafted jewelry',
    imageUrl: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?q=80&w=800&auto=format&fit=crop',
    icon: 'Watch',
    isFeatured: true,
    sortOrder: 4,
    productCount: 12,
  },
  {
    id: 'cat-5',
    name: 'Gourmet & Wellness',
    slug: 'wellness-gourmet',
    description: 'Artisanal organic teas, botanical skincare, and luxury hampers',
    imageUrl: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?q=80&w=800&auto=format&fit=crop',
    icon: 'Sparkles',
    isFeatured: false,
    sortOrder: 5,
    productCount: 20,
  },
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'prod-101',
    categoryId: 'cat-1',
    categoryName: 'Consumer Electronics',
    categorySlug: 'electronics',
    title: 'Aura Studio Wireless ANC Headphones',
    slug: 'aura-studio-wireless-anc-headphones',
    shortDescription: 'Active noise cancelling studio headphones with 45h playback & lossless audio output.',
    description: `Immerse yourself in acoustic perfection with the Aura Studio Headphones. Designed for audiophiles who demand spatial clarity and deep resonance.

Key Features:
- Hybrid Active Noise Cancellation with Transparency Mode
- Custom 45mm Titanium-coated neodymium drivers
- Ultra-soft memory foam ear cushions wrapped in breathable protein leather
- Bluetooth 5.3 with multipoint connection for seamless device switching
- Up to 45 hours battery runtime on a single 15-minute fast charge`,
    basePrice: 24999,
    salePrice: 19999,
    sku: 'SBJ-AUDIO-101',
    brand: 'Aura Sound',
    isFeatured: true,
    isNewArrival: true,
    isBestSeller: true,
    isActive: true,
    averageRating: 4.8,
    reviewCount: 42,
    inStock: true,
    tags: ['wireless', 'noise-cancelling', 'premium-audio', 'bestseller'],
    images: [
      {
        id: 'img-101-1',
        productId: 'prod-101',
        imageUrl: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?q=80&w=1000&auto=format&fit=crop',
        altText: 'Aura Studio Wireless ANC Headphones Main View',
        isPrimary: true,
        displayOrder: 1,
      },
      {
        id: 'img-101-2',
        productId: 'prod-101',
        imageUrl: 'https://images.unsplash.com/photo-1484704849700-f032a568e944?q=80&w=1000&auto=format&fit=crop',
        altText: 'Side detail of Aura Studio Headphones',
        isPrimary: false,
        displayOrder: 2,
      },
    ],
    variants: [
      {
        id: 'var-101-black',
        productId: 'prod-101',
        title: 'Obsidian Black',
        sku: 'SBJ-AUDIO-101-BLK',
        priceModifier: 0,
        attributes: { Color: 'Obsidian Black' },
        isActive: true,
      },
      {
        id: 'var-101-gold',
        productId: 'prod-101',
        title: 'Champagne Gold Edition',
        sku: 'SBJ-AUDIO-101-GLD',
        priceModifier: 2000,
        attributes: { Color: 'Champagne Gold' },
        isActive: true,
      },
    ],
    createdAt: '2026-08-01T10:00:00Z',
    updatedAt: '2026-08-20T10:00:00Z',
  },
  {
    id: 'prod-102',
    categoryId: 'cat-4',
    categoryName: 'Timepieces & Jewelry',
    categorySlug: 'watches-jewelry',
    title: 'Vanguard Automatic GMT Chronograph Watch',
    slug: 'vanguard-automatic-gmt-chronograph-watch',
    shortDescription: 'Swiss-inspired automatic movement with dual time zone bezel and sapphire crystal.',
    description: `The Vanguard Automatic GMT is crafted for global travelers and watch enthusiasts. Encased in surgical-grade 316L stainless steel with double-curved antireflective sapphire lens.

Specifications:
- Calibre: Automatic Self-winding mechanical movement with 42h power reserve
- Case Diameter: 41mm
- Water Resistance: 10 ATM (100 meters)
- Strap: Interchangeable solid stainless steel bracelet with butterfly deployment clasp`,
    basePrice: 48999,
    salePrice: 42500,
    sku: 'SBJ-WATCH-202',
    brand: 'Vanguard Horology',
    isFeatured: true,
    isNewArrival: true,
    isBestSeller: false,
    isActive: true,
    averageRating: 4.9,
    reviewCount: 19,
    inStock: true,
    tags: ['luxury-watch', 'automatic', 'swiss-movement'],
    images: [
      {
        id: 'img-102-1',
        productId: 'prod-102',
        imageUrl: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?q=80&w=1000&auto=format&fit=crop',
        altText: 'Vanguard GMT Watch Dial',
        isPrimary: true,
        displayOrder: 1,
      },
      {
        id: 'img-102-2',
        productId: 'prod-102',
        imageUrl: 'https://images.unsplash.com/photo-1524805444758-089113d48a6d?q=80&w=1000&auto=format&fit=crop',
        altText: 'Wrist Shot Vanguard Watch',
        isPrimary: false,
        displayOrder: 2,
      },
    ],
    createdAt: '2026-08-05T12:00:00Z',
    updatedAt: '2026-08-21T12:00:00Z',
  },
  {
    id: 'prod-103',
    categoryId: 'cat-2',
    categoryName: 'Luxury Apparel',
    categorySlug: 'apparel',
    title: 'Heritage Mulberry Silk Kurta Jacket Set',
    slug: 'heritage-mulberry-silk-kurta-jacket-set',
    shortDescription: 'Handwoven pure mulberry silk structured jacket paired with a tailored tailored kurta.',
    description: `Exude timeless elegance at celebratory occasions with our Heritage Mulberry Silk Set. Featuring intricate threadwork on a refined neutral palette.

Includes:
- Structured Mulberry Silk Nehru Jacket
- Fine Cotton-Silk Base Kurta
- Tapered Silk Churidar Trousers`,
    basePrice: 18999,
    salePrice: 15999,
    sku: 'SBJ-ETHNIC-303',
    brand: 'Jitesh Couture',
    isFeatured: true,
    isNewArrival: false,
    isBestSeller: true,
    isActive: true,
    averageRating: 4.7,
    reviewCount: 31,
    inStock: true,
    tags: ['ethic-wear', 'festive', 'designer-kurta'],
    images: [
      {
        id: 'img-103-1',
        productId: 'prod-103',
        imageUrl: 'https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?q=80&w=1000&auto=format&fit=crop',
        altText: 'Heritage Mulberry Silk Kurta Set',
        isPrimary: true,
        displayOrder: 1,
      },
    ],
    createdAt: '2026-08-02T09:00:00Z',
    updatedAt: '2026-08-18T09:00:00Z',
  },
  {
    id: 'prod-104',
    categoryId: 'cat-3',
    categoryName: 'Home & Living',
    categorySlug: 'home-living',
    title: 'Nordic Ceramic Sculptural Table Lamp',
    slug: 'nordic-ceramic-sculptural-table-lamp',
    shortDescription: 'Warm ambient ceramic table lamp with dimmable warm LED bulb & linen shade.',
    description: `Elevate your living spaces with serene warm light. Hand-cast ceramic base featuring an organic textured surface paired with a tailored natural linen drum shade.`,
    basePrice: 8999,
    salePrice: 7499,
    sku: 'SBJ-DECOR-404',
    brand: 'Lumina Living',
    isFeatured: false,
    isNewArrival: true,
    isBestSeller: false,
    isActive: true,
    averageRating: 4.6,
    reviewCount: 14,
    inStock: true,
    tags: ['home-decor', 'lighting', 'nordic'],
    images: [
      {
        id: 'img-104-1',
        productId: 'prod-104',
        imageUrl: 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?q=80&w=1000&auto=format&fit=crop',
        altText: 'Nordic Sculptural Lamp',
        isPrimary: true,
        displayOrder: 1,
      },
    ],
    createdAt: '2026-08-10T11:00:00Z',
    updatedAt: '2026-08-22T11:00:00Z',
  },
  {
    id: 'prod-105',
    categoryId: 'cat-5',
    categoryName: 'Gourmet & Wellness',
    categorySlug: 'wellness-gourmet',
    title: 'Botanical Elixir Facial Serum & Rose Quartz Roller',
    slug: 'botanical-elixir-facial-serum-rose-quartz-roller',
    shortDescription: 'Cold-pressed organic rosehip & saffron oil infused serum with natural rose quartz applicator.',
    description: `Rejuvenate your skin with 100% pure cold-pressed botanical oils infused with Kashmiri Saffron extract and Bakuchiol for radiant youthfulness.`,
    basePrice: 4499,
    salePrice: 3899,
    sku: 'SBJ-SKIN-505',
    brand: 'Aetheria Botanicals',
    isFeatured: true,
    isNewArrival: true,
    isBestSeller: true,
    isActive: true,
    averageRating: 4.9,
    reviewCount: 56,
    inStock: true,
    tags: ['skincare', 'organic', 'gourmet-wellness'],
    images: [
      {
        id: 'img-105-1',
        productId: 'prod-105',
        imageUrl: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?q=80&w=1000&auto=format&fit=crop',
        altText: 'Botanical Serum Bottle',
        isPrimary: true,
        displayOrder: 1,
      },
    ],
    createdAt: '2026-08-08T08:00:00Z',
    updatedAt: '2026-08-23T08:00:00Z',
  },
];

export const MOCK_COUPONS: Coupon[] = [
  {
    id: 'coup-1',
    code: 'JITESH10',
    description: 'Get 10% instant discount on your first luxury order',
    discountType: 'percentage',
    discountValue: 10,
    minimumOrderAmount: 2000,
    maxDiscountAmount: 3000,
    validUntil: '2026-12-31T23:59:59Z',
    isActive: true,
  },
  {
    id: 'coup-2',
    code: 'FESTIVE500',
    description: 'Flat ₹500 off on orders above ₹4,999',
    discountType: 'fixed_amount',
    discountValue: 500,
    minimumOrderAmount: 4999,
    validUntil: '2026-10-31T23:59:59Z',
    isActive: true,
  },
];
