import mysql from 'mysql2/promise';
import dotenv from 'dotenv';
import path from 'path';

dotenv.config({ path: path.resolve(process.cwd(), '.env.local') });

interface ProductSeedItem {
  id: string;
  categoryId: string;
  title: string;
  slug: string;
  shortDescription: string;
  description: string;
  basePrice: number;
  salePrice: number | null;
  sku: string;
  brand: string;
  isFeatured: boolean;
  isNewArrival: boolean;
  isBestSeller: boolean;
  rating: number;
  reviews: number;
  tags: string[];
  imageUrl: string;
  stock: number;
}

const CATEGORIES_DATA = [
  {
    id: 'cat-1',
    parentId: null,
    name: 'Consumer Electronics',
    slug: 'electronics',
    description: 'Next-gen audio, smart wearables, monitors, and personal tech essentials.',
    imageUrl: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?q=80&w=800&auto=format&fit=crop',
    icon: 'Laptop',
    isFeatured: true,
    sortOrder: 1,
  },
  {
    id: 'cat-2',
    parentId: null,
    name: 'Apparel & Fashion',
    slug: 'apparel',
    description: 'Tailored ethnic wear, outerwear, denim, and modern luxury fits.',
    imageUrl: 'https://images.unsplash.com/photo-1489987707025-afc232f7ea0f?q=80&w=800&auto=format&fit=crop',
    icon: 'Shirt',
    isFeatured: true,
    sortOrder: 2,
  },
  {
    id: 'cat-3',
    parentId: null,
    name: 'Home & Living',
    slug: 'home-living',
    description: 'Handcrafted decor, warm lighting, cookware, and artisanal furniture.',
    imageUrl: 'https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?q=80&w=800&auto=format&fit=crop',
    icon: 'Home',
    isFeatured: true,
    sortOrder: 3,
  },
  {
    id: 'cat-4',
    parentId: null,
    name: 'Timepieces & Accessories',
    slug: 'watches-jewelry',
    description: 'Precision chronograph watches, leather craft, and heritage accessories.',
    imageUrl: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?q=80&w=800&auto=format&fit=crop',
    icon: 'Watch',
    isFeatured: true,
    sortOrder: 4,
  },
  {
    id: 'cat-5',
    parentId: null,
    name: 'Beauty & Wellness',
    slug: 'wellness-gourmet',
    description: 'Artisanal organic skincare, botanical oils, teas, and wellness hampers.',
    imageUrl: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?q=80&w=800&auto=format&fit=crop',
    icon: 'Sparkles',
    isFeatured: true,
    sortOrder: 5,
  },
];

const PRODUCTS_DATA: ProductSeedItem[] = [
  // ================= CATEGORY 1: ELECTRONICS (21 Products) =================
  {
    id: 'prod-201',
    categoryId: 'cat-1',
    title: 'Aura Studio Wireless ANC Headphones',
    slug: 'aura-studio-wireless-anc-headphones',
    shortDescription: 'Active noise cancelling studio headphones with 45h playback & lossless audio output.',
    description: 'Immerse yourself in acoustic perfection with the Aura Studio Headphones featuring hybrid active noise cancellation, custom 40mm beryllium drivers, multipoint Bluetooth 5.3, and ultra-soft memory foam ear cushions.',
    basePrice: 24999.00,
    salePrice: 19999.00,
    sku: 'SBJ-ELEC-201',
    brand: 'Aura Sound',
    isFeatured: true,
    isNewArrival: true,
    isBestSeller: true,
    rating: 4.8,
    reviews: 64,
    tags: ['wireless', 'audio', 'headphones', 'anc'],
    imageUrl: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?q=80&w=1000',
    stock: 45,
  },
  {
    id: 'prod-202',
    categoryId: 'cat-1',
    title: 'AeroBuds Pro True Wireless Earbuds',
    slug: 'aerobuds-pro-true-wireless-earbuds',
    shortDescription: 'Spatial audio TWS earbuds with IPX7 water resistance & wireless charging case.',
    description: 'AeroBuds Pro delivers immersive 360-degree spatial audio with low-latency gaming mode, dual microphones for crystal clear calls, and a total 32-hour battery life.',
    basePrice: 8999.00,
    salePrice: 6999.00,
    sku: 'SBJ-ELEC-202',
    brand: 'Aura Sound',
    isFeatured: true,
    isNewArrival: true,
    isBestSeller: false,
    rating: 4.6,
    reviews: 38,
    tags: ['tws', 'earbuds', 'wireless', 'audio'],
    imageUrl: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?q=80&w=1000',
    stock: 60,
  },
  {
    id: 'prod-203',
    categoryId: 'cat-1',
    title: 'PulseFit Horizon OLED Smartwatch',
    slug: 'pulsefit-horizon-oled-smartwatch',
    shortDescription: '1.43" HD AMOLED smartwatch with ECG, SpO2, GPS & titanium alloy chassis.',
    description: 'Track your health and fitness with military-grade precision. Features continuous heart rate monitoring, sleep tracking, 100+ sports modes, and 14-day battery backup.',
    basePrice: 14999.00,
    salePrice: 11999.00,
    sku: 'SBJ-ELEC-203',
    brand: 'PulseFit',
    isFeatured: true,
    isNewArrival: false,
    isBestSeller: true,
    rating: 4.7,
    reviews: 52,
    tags: ['smartwatch', 'wearable', 'fitness', 'oled'],
    imageUrl: 'https://images.unsplash.com/photo-1546868871-7041f2a55e12?q=80&w=1000',
    stock: 35,
  },
  {
    id: 'prod-204',
    categoryId: 'cat-1',
    title: 'PrecisionKey Pro RGB Mechanical Keyboard',
    slug: 'precisionkey-pro-rgb-mechanical-keyboard',
    shortDescription: 'Hot-swappable tactile mechanical keyboard with CNC aluminum top plate & wireless tri-mode.',
    description: 'Engineered for coders and creators. Features pre-lubed linear switches, PBT double-shot keycaps, per-key RGB backlighting, and 2.4GHz/Bluetooth/USB-C connection modes.',
    basePrice: 12999.00,
    salePrice: 9999.00,
    sku: 'SBJ-ELEC-204',
    brand: 'PrecisionKey',
    isFeatured: false,
    isNewArrival: true,
    isBestSeller: true,
    rating: 4.9,
    reviews: 81,
    tags: ['keyboard', 'mechanical', 'rgb', 'tech'],
    imageUrl: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?q=80&w=1000',
    stock: 25,
  },
  {
    id: 'prod-205',
    categoryId: 'cat-1',
    title: 'VividView 27-inch 4K HDR USB-C Monitor',
    slug: 'vividview-27-inch-4k-hdr-usbc-monitor',
    shortDescription: '99% DCI-P3 color accurate IPS display with 90W USB-C power delivery & ultra-thin bezel.',
    description: 'Designed for visual artists, designers, and software engineers. Offers 3840x2160 resolution, factory-calibrated color accuracy, ergonomic height-adjustable stand, and single-cable laptop connection.',
    basePrice: 42999.00,
    salePrice: 36999.00,
    sku: 'SBJ-ELEC-205',
    brand: 'VividView',
    isFeatured: true,
    isNewArrival: false,
    isBestSeller: false,
    rating: 4.8,
    reviews: 29,
    tags: ['monitor', '4k', 'display', 'workspace'],
    imageUrl: 'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?q=80&w=1000',
    stock: 18,
  },
  {
    id: 'prod-206',
    categoryId: 'cat-1',
    title: 'SonicBoom Portable Bluetooth Speaker',
    slug: 'sonicboom-portable-bluetooth-speaker',
    shortDescription: '30W stereo outdoor speaker with IP67 waterproofing & 24-hour battery powerbank.',
    description: 'Fill any space with deep bass and clear highs. Built with rugged shockproof casing, dual passive radiators, and integrated powerbank to charge your phone on the go.',
    basePrice: 6999.00,
    salePrice: 4999.00,
    sku: 'SBJ-ELEC-206',
    brand: 'Aura Sound',
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: true,
    rating: 4.5,
    reviews: 47,
    tags: ['speaker', 'bluetooth', 'audio', 'portable'],
    imageUrl: 'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?q=80&w=1000',
    stock: 50,
  },
  {
    id: 'prod-207',
    categoryId: 'cat-1',
    title: 'StreamCam 4K Ultra HD Webcam',
    slug: 'streamcam-4k-ultra-hd-webcam',
    shortDescription: '4K 60fps HDR webcam with dual noise-reduction mic & magnetic privacy shutter.',
    description: 'Look your best on video calls and live streams. Features AI auto-framing, low-light compensation, stereo noise-cancelling microphones, and universal tripod mount.',
    basePrice: 11999.00,
    salePrice: 8999.00,
    sku: 'SBJ-ELEC-207',
    brand: 'VividView',
    isFeatured: false,
    isNewArrival: true,
    isBestSeller: false,
    rating: 4.6,
    reviews: 23,
    tags: ['webcam', '4k', 'streaming', 'tech'],
    imageUrl: 'https://images.unsplash.com/photo-1588702547919-26089e690ecc?q=80&w=1000',
    stock: 30,
  },
  {
    id: 'prod-208',
    categoryId: 'cat-1',
    title: 'VoltFast 100W GaN Desktop Charger',
    slug: 'voltfast-100w-gan-desktop-charger',
    shortDescription: 'Ultra-compact 4-port GaN III fast charger for laptops, phones & tablets.',
    description: 'Replace bulky power bricks with one sleek desktop charger. Delivers up to 100W USB-C Power Delivery, fast-charging 4 devices simultaneously with intelligent power allocation.',
    basePrice: 4999.00,
    salePrice: 3799.00,
    sku: 'SBJ-ELEC-208',
    brand: 'VoltFast',
    isFeatured: false,
    isNewArrival: true,
    isBestSeller: true,
    rating: 4.9,
    reviews: 73,
    tags: ['charger', 'gan', 'usbc', 'power'],
    imageUrl: 'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?q=80&w=1000',
    stock: 75,
  },
  {
    id: 'prod-209',
    categoryId: 'cat-1',
    title: 'MagSafe Wireless Power Bank 10,000mAh',
    slug: 'magsafe-wireless-power-bank-10000mah',
    shortDescription: '15W magnetic wireless powerbank with pass-through charging & foldable kickstand.',
    description: 'Snap on for effortless charging. Features strong neodymium magnets, LED battery display, USB-C 20W wired output, and slim aerospace aluminum finish.',
    basePrice: 3999.00,
    salePrice: 2999.00,
    sku: 'SBJ-ELEC-209',
    brand: 'VoltFast',
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: true,
    rating: 4.7,
    reviews: 92,
    tags: ['powerbank', 'magsafe', 'wireless', 'accessories'],
    imageUrl: 'https://images.unsplash.com/photo-1609592424074-8848db9276d4?q=80&w=1000',
    stock: 80,
  },
  {
    id: 'prod-210',
    categoryId: 'cat-1',
    title: 'ErgoGlide Wireless Ergonomic Mouse',
    slug: 'ergoglide-wireless-ergonomic-mouse',
    shortDescription: 'Vertical ergonomic wireless mouse with silent clicks & thumb scroll wheel.',
    description: 'Reduce wrist strain during long work hours. Features 57-degree natural handshake angle, 4000 DPI precision optical sensor, and Bluetooth/2.4GHz dual connection.',
    basePrice: 3499.00,
    salePrice: null,
    sku: 'SBJ-ELEC-210',
    brand: 'PrecisionKey',
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: false,
    rating: 4.4,
    reviews: 31,
    tags: ['mouse', 'ergonomic', 'workspace', 'wireless'],
    imageUrl: 'https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?q=80&w=1000',
    stock: 40,
  },
  {
    id: 'prod-211',
    categoryId: 'cat-1',
    title: 'TitanDrive 2TB Portable NVMe SSD',
    slug: 'titandrive-2tb-portable-nvme-ssd',
    shortDescription: 'Rugged USB 3.2 Gen 2x2 external SSD with up to 2000MB/s read speed.',
    description: 'Blazing fast storage for video editors and gamers. Drop-resistant up to 2 meters with IP55 water/dust resistance and hardware 256-bit AES encryption.',
    basePrice: 18999.00,
    salePrice: 14999.00,
    sku: 'SBJ-ELEC-211',
    brand: 'TitanDrive',
    isFeatured: false,
    isNewArrival: true,
    isBestSeller: false,
    rating: 4.8,
    reviews: 19,
    tags: ['ssd', 'storage', 'nvme', 'tech'],
    imageUrl: 'https://images.unsplash.com/photo-1597872200969-2b65d56bd16b?q=80&w=1000',
    stock: 20,
  },
  {
    id: 'prod-212',
    categoryId: 'cat-1',
    title: 'StudioPod Condenser USB Microphone',
    slug: 'studiopod-condenser-usb-microphone',
    shortDescription: 'Professional cardioid USB microphone with zero-latency monitoring & pop filter.',
    description: 'Capture broadcast-quality vocals for podcasting, voiceovers, and gaming. Comes with heavy-duty metal desktop stand, gain control knob, and tap-to-mute sensor.',
    basePrice: 7999.00,
    salePrice: 5999.00,
    sku: 'SBJ-ELEC-212',
    brand: 'Aura Sound',
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: true,
    rating: 4.7,
    reviews: 58,
    tags: ['microphone', 'podcast', 'audio', 'usb'],
    imageUrl: 'https://images.unsplash.com/photo-1590602847861-f357a9332bbc?q=80&w=1000',
    stock: 32,
  },
  {
    id: 'prod-213',
    categoryId: 'cat-1',
    title: 'SmartHome Hub 4K Streaming Stick',
    slug: 'smarthome-hub-4k-streaming-stick',
    shortDescription: 'Android TV 12 media streamer with Dolby Vision, Atmos & voice remote.',
    description: 'Transform any TV into a smart entertainment center. Supports Netflix 4K HDR, Prime Video, YouTube, dual-band Wi-Fi 6, and Google Assistant voice commands.',
    basePrice: 4499.00,
    salePrice: 3499.00,
    sku: 'SBJ-ELEC-213',
    brand: 'VividView',
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: true,
    rating: 4.5,
    reviews: 110,
    tags: ['streaming', 'tv', 'smarthome', 'tech'],
    imageUrl: 'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?q=80&w=1000',
    stock: 90,
  },
  {
    id: 'prod-214',
    categoryId: 'cat-1',
    title: 'LuminaGlow RGB Desk Light Bar',
    slug: 'luminaglow-rgb-desk-light-bar',
    shortDescription: 'Screen-hanging LED lamp with ambient backlighting & wireless touch dial.',
    description: 'Eliminate screen glare and eye fatigue. Features asymmetrical optical design, customizable color temperature (2700K-6500K), and music sync RGB ambient lighting.',
    basePrice: 5999.00,
    salePrice: 4499.00,
    sku: 'SBJ-ELEC-214',
    brand: 'PrecisionKey',
    isFeatured: false,
    isNewArrival: true,
    isBestSeller: false,
    rating: 4.6,
    reviews: 34,
    tags: ['lighting', 'desk', 'workspace', 'rgb'],
    imageUrl: 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?q=80&w=1000',
    stock: 45,
  },
  {
    id: 'prod-215',
    categoryId: 'cat-1',
    title: 'CinePro 1080p Full HD Portable Projector',
    slug: 'cinepro-1080p-full-hd-portable-projector',
    shortDescription: 'Compact 500 ANSI lumen smart projector with autofocus & auto keystone.',
    description: 'Enjoy home theater screen sizes up to 150 inches anywhere. Built-in Harman-tuned dual speakers, Wi-Fi screen mirroring, and HDMI/USB connectivity.',
    basePrice: 29999.00,
    salePrice: 24999.00,
    sku: 'SBJ-ELEC-215',
    brand: 'VividView',
    isFeatured: true,
    isNewArrival: false,
    isBestSeller: false,
    rating: 4.7,
    reviews: 26,
    tags: ['projector', 'home-theater', 'video', 'cinema'],
    imageUrl: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?q=80&w=1000',
    stock: 15,
  },
  {
    id: 'prod-216',
    categoryId: 'cat-1',
    title: 'FlexiArm Dual Monitor Gas Spring Mount',
    slug: 'flexiarm-dual-monitor-gas-spring-mount',
    shortDescription: 'Heavy-duty aluminum dual monitor arm for 17"-32" screens with cable management.',
    description: 'Reclaim desktop space with smooth 360-degree rotation, tilt, and height adjustment. Supports VESA 75x75 and 100x100 standards up to 9kg per arm.',
    basePrice: 4999.00,
    salePrice: 3999.00,
    sku: 'SBJ-ELEC-216',
    brand: 'PrecisionKey',
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: false,
    rating: 4.6,
    reviews: 18,
    tags: ['mount', 'monitor', 'desk', 'ergonomic'],
    imageUrl: 'https://images.unsplash.com/photo-1593640408182-31c70c8268f5?q=80&w=1000',
    stock: 25,
  },
  {
    id: 'prod-217',
    categoryId: 'cat-1',
    title: 'Aura Gaming Wireless Headset 7.1',
    slug: 'aura-gaming-wireless-headset-71',
    shortDescription: '7.1 surround sound gaming headset with detachable noise-cancelling boom mic.',
    description: 'Hear every footstep with ultra-low latency 2.4GHz wireless transmission, 50mm neodymium drivers, breathable mesh ear pads, and RGB earcups.',
    basePrice: 10999.00,
    salePrice: 8499.00,
    sku: 'SBJ-ELEC-217',
    brand: 'Aura Sound',
    isFeatured: false,
    isNewArrival: true,
    isBestSeller: false,
    rating: 4.7,
    reviews: 41,
    tags: ['gaming', 'headset', 'surround-sound', 'audio'],
    imageUrl: 'https://images.unsplash.com/photo-1618366712010-f4ae9c647dcb?q=80&w=1000',
    stock: 30,
  },
  {
    id: 'prod-218',
    categoryId: 'cat-1',
    title: 'PocketView 15.6-inch Full HD Portable Monitor',
    slug: 'pocketview-156-inch-full-hd-portable-monitor',
    shortDescription: 'Ultra-thin IPS second screen for laptops with dual USB-C & magnetic cover.',
    description: 'Boost mobile productivity with a lightweight 750g portable display. Plug and play with Mac, Windows, Android, and Nintendo Switch.',
    basePrice: 16999.00,
    salePrice: 13999.00,
    sku: 'SBJ-ELEC-218',
    brand: 'VividView',
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: false,
    rating: 4.5,
    reviews: 22,
    tags: ['portable-monitor', 'display', 'laptop', 'workspace'],
    imageUrl: 'https://images.unsplash.com/photo-1541807084-5c52b6b3adef?q=80&w=1000',
    stock: 20,
  },
  {
    id: 'prod-219',
    categoryId: 'cat-1',
    title: 'VoltFast 3-in-1 Foldable Charging Station',
    slug: 'voltfast-3in1-foldable-charging-station',
    shortDescription: 'Qi wireless charger for iPhone, Apple Watch & AirPods simultaneously.',
    description: 'Clean up desk clutter with a compact travel-friendly wireless pad. Features intelligent temperature protection, soft-touch silicone matte finish, and LED indicators.',
    basePrice: 4299.00,
    salePrice: 3299.00,
    sku: 'SBJ-ELEC-219',
    brand: 'VoltFast',
    isFeatured: false,
    isNewArrival: true,
    isBestSeller: true,
    rating: 4.8,
    reviews: 67,
    tags: ['wireless-charger', 'apple', 'magsafe', 'accessories'],
    imageUrl: 'https://images.unsplash.com/photo-1622445268465-843d61182283?q=80&w=1000',
    stock: 55,
  },
  {
    id: 'prod-220',
    categoryId: 'cat-1',
    title: 'PrecisionPad XL Stitch-Edge Desk Mat',
    slug: 'precisionpad-xl-stitch-edge-desk-mat',
    shortDescription: '900x400mm waterproof micro-weave cloth mouse pad with anti-slip rubber base.',
    description: 'Provide smooth tracking for high-DPI gaming and work setups. Machine-washable surface with reinforced anti-fray stitched edges.',
    basePrice: 1999.00,
    salePrice: 1499.00,
    sku: 'SBJ-ELEC-220',
    brand: 'PrecisionKey',
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: true,
    rating: 4.9,
    reviews: 140,
    tags: ['deskmat', 'mousepad', 'workspace', 'accessories'],
    imageUrl: 'https://images.unsplash.com/photo-1616440342855-467f3a8b417c?q=80&w=1000',
    stock: 100,
  },
  {
    id: 'prod-221',
    categoryId: 'cat-1',
    title: 'ProCam 4K Vlogging Action Camera',
    slug: 'procam-4k-vlogging-action-camera',
    shortDescription: 'Dual-screen 4K 60fps waterproof camera with 6-axis electronic image stabilization.',
    description: 'Capture extreme sports and daily vlogs in vivid detail. Includes 30m underwater housing, touch control rear display, and front selfie preview screen.',
    basePrice: 21999.00,
    salePrice: 17999.00,
    sku: 'SBJ-ELEC-221',
    brand: 'VividView',
    isFeatured: true,
    isNewArrival: true,
    isBestSeller: false,
    rating: 4.6,
    reviews: 29,
    tags: ['camera', 'action-cam', '4k', 'vlogging'],
    imageUrl: 'https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?q=80&w=1000',
    stock: 22,
  },

  // ================= CATEGORY 2: APPAREL & FASHION (21 Products) =================
  {
    id: 'prod-222',
    categoryId: 'cat-2',
    title: 'Heritage Mulberry Silk Kurta Jacket Set',
    slug: 'heritage-mulberry-silk-kurta-jacket-set',
    shortDescription: 'Handwoven pure mulberry silk structured jacket paired with a tailored kurta.',
    description: 'Exude timeless elegance at celebratory occasions with our Heritage Mulberry Silk Set. Features intricate zari thread work and breathable cotton-silk lining.',
    basePrice: 18999.00,
    salePrice: 15999.00,
    sku: 'SBJ-ETHNIC-303',
    brand: 'Jitesh Couture',
    isFeatured: true,
    isNewArrival: false,
    isBestSeller: true,
    rating: 4.8,
    reviews: 35,
    tags: ['ethnic', 'silk', 'kurta', 'festive'],
    imageUrl: 'https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?q=80&w=1000',
    stock: 20,
  },
  {
    id: 'prod-223',
    categoryId: 'cat-2',
    title: 'Oversized Heavyweight Organic Cotton Hoodie',
    slug: 'oversized-heavyweight-organic-cotton-hoodie',
    shortDescription: '450 GSM fleece-lined French terry cotton hoodie in washed obsidian charcoal.',
    description: 'The ultimate streetwear staple. Designed with dropped shoulders, double-layered hood, kangaroo pocket, and rib-knit cuffs.',
    basePrice: 4999.00,
    salePrice: 3999.00,
    sku: 'SBJ-FASH-223',
    brand: 'UrbanThread',
    isFeatured: true,
    isNewArrival: true,
    isBestSeller: true,
    rating: 4.9,
    reviews: 88,
    tags: ['hoodie', 'streetwear', 'cotton', 'oversized'],
    imageUrl: 'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?q=80&w=1000',
    stock: 50,
  },
  {
    id: 'prod-224',
    categoryId: 'cat-2',
    title: 'Italian Wool Blend Double-Breasted Trench Coat',
    slug: 'italian-wool-blend-double-breasted-trench-coat',
    shortDescription: 'Tailored luxury winter trench coat with horn buttons & waist belt.',
    description: 'Crafted from premium Italian virgin wool blend. Features classic lapels, storm flap, rear vent, and deep welt pockets.',
    basePrice: 22999.00,
    salePrice: 18999.00,
    sku: 'SBJ-FASH-224',
    brand: 'Jitesh Couture',
    isFeatured: true,
    isNewArrival: true,
    isBestSeller: false,
    rating: 4.9,
    reviews: 19,
    tags: ['coat', 'wool', 'winter', 'luxury'],
    imageUrl: 'https://images.unsplash.com/photo-1539533018447-63fcce2678e3?q=80&w=1000',
    stock: 15,
  },
  {
    id: 'prod-225',
    categoryId: 'cat-2',
    title: 'Raw Denim Selvedge Slim-Fit Jeans',
    slug: 'raw-denim-selvedge-slim-fit-jeans',
    shortDescription: '14 oz Japanese shuttle-loom indigo selvedge denim with custom brass hardware.',
    description: 'Built to age beautifully with personal wear patterns. Features copper rivets, button fly, and red selvedge ID ticker stitch.',
    basePrice: 6999.00,
    salePrice: 5499.00,
    sku: 'SBJ-FASH-225',
    brand: 'UrbanThread',
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: true,
    rating: 4.7,
    reviews: 62,
    tags: ['denim', 'jeans', 'selvedge', 'casual'],
    imageUrl: 'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?q=80&w=1000',
    stock: 40,
  },
  {
    id: 'prod-226',
    categoryId: 'cat-2',
    title: 'Pure Linen Resort Collar Cuban Shirt',
    slug: 'pure-linen-resort-collar-cuban-shirt',
    shortDescription: '100% European flax breathable linen summer shirt in ivory cream.',
    description: 'Stay cool during warm getaways. Designed with relaxed camp collar, mother-of-pearl buttons, and lightweight airy texture.',
    basePrice: 3499.00,
    salePrice: 2799.00,
    sku: 'SBJ-FASH-226',
    brand: 'UrbanThread',
    isFeatured: false,
    isNewArrival: true,
    isBestSeller: true,
    rating: 4.6,
    reviews: 43,
    tags: ['linen', 'shirt', 'summer', 'vacation'],
    imageUrl: 'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?q=80&w=1000',
    stock: 45,
  },
  {
    id: 'prod-227',
    categoryId: 'cat-2',
    title: 'Chanderi Handloom Embroidered Saree',
    slug: 'chanderi-handloom-embroidered-saree',
    shortDescription: 'Traditional tissue silk-cotton saree with gold zari motifs & unstitched blouse.',
    description: 'Woven by master artisans in Madhya Pradesh. Features lightweight sheer texture, metallic zari borders, and soft fluid drape.',
    basePrice: 12999.00,
    salePrice: 10499.00,
    sku: 'SBJ-FASH-227',
    brand: 'Jitesh Couture',
    isFeatured: true,
    isNewArrival: false,
    isBestSeller: true,
    rating: 4.8,
    reviews: 51,
    tags: ['saree', 'ethnic', 'handloom', 'chanderi'],
    imageUrl: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?q=80&w=1000',
    stock: 25,
  },
  {
    id: 'prod-228',
    categoryId: 'cat-2',
    title: 'Genuine Calfskin Leather Biker Jacket',
    slug: 'genuine-calfskin-leather-biker-jacket',
    shortDescription: 'Full-grain leather moto jacket with YKK brass zippers & quilted viscose lining.',
    description: 'Iconic rebel style crafted from supple full-grain calfskin leather. Features asymmetric front zip, snap collar, zipper cuffs, and interior wallet pockets.',
    basePrice: 27999.00,
    salePrice: 22999.00,
    sku: 'SBJ-FASH-228',
    brand: 'Jitesh Couture',
    isFeatured: false,
    isNewArrival: true,
    isBestSeller: false,
    rating: 4.9,
    reviews: 27,
    tags: ['leather', 'jacket', 'biker', 'outerwear'],
    imageUrl: 'https://images.unsplash.com/photo-1521223890158-f9f7c3d5d504?q=80&w=1000',
    stock: 12,
  },
  {
    id: 'prod-229',
    categoryId: 'cat-2',
    title: 'Merino Wool Crewneck Knit Sweater',
    slug: 'merino-wool-crewneck-knit-sweater',
    shortDescription: 'Superfine 100% Australian Merino wool lightweight winter sweater.',
    description: 'Naturally thermoregulating and itch-free. Features fine gauge knit structure, ribbed collar and hem, and classic tailored silhouette.',
    basePrice: 5999.00,
    salePrice: 4499.00,
    sku: 'SBJ-FASH-229',
    brand: 'UrbanThread',
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: false,
    rating: 4.7,
    reviews: 36,
    tags: ['merino', 'sweater', 'knitwear', 'winter'],
    imageUrl: 'https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?q=80&w=1000',
    stock: 35,
  },
  {
    id: 'prod-230',
    categoryId: 'cat-2',
    title: 'Tailored Unstructured Cotton Linen Blazer',
    slug: 'tailored-unstructured-cotton-linen-blazer',
    shortDescription: 'Smart-casual summer blazer with patch pockets & notch lapel.',
    description: 'Drape effortlessly from business lunches to evening dinners. Features soft shoulder padding, unlined interior for max breathability, and double vent back.',
    basePrice: 9999.00,
    salePrice: 7999.00,
    sku: 'SBJ-FASH-230',
    brand: 'Jitesh Couture',
    isFeatured: false,
    isNewArrival: true,
    isBestSeller: false,
    rating: 4.6,
    reviews: 24,
    tags: ['blazer', 'suit', 'tailored', 'menswear'],
    imageUrl: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?q=80&w=1000',
    stock: 20,
  },
  {
    id: 'prod-231',
    categoryId: 'cat-2',
    title: 'Minimalist White Leather Low-Top Sneakers',
    slug: 'minimalist-white-leather-low-top-sneakers',
    shortDescription: 'Full-grain Italian nappa leather sneakers with stitched Margom rubber sole.',
    description: 'Clean aesthetic suitable for formal and casual outfits alike. Handcrafted with plush calfskin lining and waxed cotton laces.',
    basePrice: 7999.00,
    salePrice: 6499.00,
    sku: 'SBJ-FASH-231',
    brand: 'UrbanThread',
    isFeatured: true,
    isNewArrival: false,
    isBestSeller: true,
    rating: 4.8,
    reviews: 95,
    tags: ['sneakers', 'shoes', 'leather', 'footwear'],
    imageUrl: 'https://images.unsplash.com/photo-1549298916-b41d501d3772?q=80&w=1000',
    stock: 60,
  },
  {
    id: 'prod-232',
    categoryId: 'cat-2',
    title: 'Hand-Block Printed Cotton Anarkali Dress',
    slug: 'hand-block-printed-cotton-anarkali-dress',
    shortDescription: 'Bagru hand-block floral print flared cotton dress with dupatta.',
    description: 'Celebrate Indian heritage print crafts. Features tiered flared silhouette, gota patti embroidery highlights, and soft breathable mulmul cotton.',
    basePrice: 5499.00,
    salePrice: 4299.00,
    sku: 'SBJ-FASH-232',
    brand: 'Jitesh Couture',
    isFeatured: false,
    isNewArrival: true,
    isBestSeller: false,
    rating: 4.7,
    reviews: 48,
    tags: ['anarkali', 'ethnic', 'cotton', 'dress'],
    imageUrl: 'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?q=80&w=1000',
    stock: 30,
  },
  {
    id: 'prod-233',
    categoryId: 'cat-2',
    title: 'Water-Resistant Technical Cargo Joggers',
    slug: 'water-resistant-technical-cargo-joggers',
    shortDescription: 'Stretch nylon techwear pants with magnetic Fidlock cargo pockets.',
    description: 'Engineered for modern urban commuters. Features DWR water-repellent coating, articulated knee panels, elastic cuffs, and zippered utility pockets.',
    basePrice: 4499.00,
    salePrice: 3499.00,
    sku: 'SBJ-FASH-233',
    brand: 'UrbanThread',
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: true,
    rating: 4.6,
    reviews: 57,
    tags: ['cargo', 'joggers', 'techwear', 'pants'],
    imageUrl: 'https://images.unsplash.com/photo-1517445312882-bc9910d016b7?q=80&w=1000',
    stock: 40,
  },
  {
    id: 'prod-234',
    categoryId: 'cat-2',
    title: 'Classic Wool-Blend Fedora Hat',
    slug: 'classic-wool-blend-fedora-hat',
    shortDescription: 'Structured wide-brim felt hat with grosgrain ribbon band.',
    description: 'Add sophisticated charm to winter outerwear. Features interior sweatband and shape-retentive wool felt construction.',
    basePrice: 2499.00,
    salePrice: null,
    sku: 'SBJ-FASH-234',
    brand: 'Jitesh Couture',
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: false,
    rating: 4.5,
    reviews: 14,
    tags: ['hat', 'fedora', 'accessories', 'fashion'],
    imageUrl: 'https://images.unsplash.com/photo-1514327605112-b887c0e61c0a?q=80&w=1000',
    stock: 25,
  },
  {
    id: 'prod-235',
    categoryId: 'cat-2',
    title: 'Pima Cotton Heavyweight Crewneck T-Shirt',
    slug: 'pima-cotton-heavyweight-crewneck-tshirt',
    shortDescription: '220 GSM Peruvian Pima long-staple cotton essential t-shirt.',
    description: 'Silky smooth touch that resists pilling and fading over dozens of washes. Pre-shrunk fit with reinforced twin-needle stitching.',
    basePrice: 1999.00,
    salePrice: 1499.00,
    sku: 'SBJ-FASH-235',
    brand: 'UrbanThread',
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: true,
    rating: 4.8,
    reviews: 112,
    tags: ['tshirt', 'cotton', 'basics', 'casual'],
    imageUrl: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?q=80&w=1000',
    stock: 120,
  },
  {
    id: 'prod-236',
    categoryId: 'cat-2',
    title: 'Suede Chelsea Boots with Goodyear Welt',
    slug: 'suede-chelsea-boots-with-goodyear-welt',
    shortDescription: 'Italian calf suede ankle boots with elastic side gussets & crepe rubber sole.',
    description: 'Handmade heritage footwear built for comfort. Resoleable Goodyear welt construction ensures lifetime durability.',
    basePrice: 11999.00,
    salePrice: 9499.00,
    sku: 'SBJ-FASH-236',
    brand: 'Jitesh Couture',
    isFeatured: false,
    isNewArrival: true,
    isBestSeller: false,
    rating: 4.9,
    reviews: 33,
    tags: ['boots', 'chelsea', 'suede', 'footwear'],
    imageUrl: 'https://images.unsplash.com/photo-1638247025967-b4e38f787b76?q=80&w=1000',
    stock: 18,
  },
  {
    id: 'prod-237',
    categoryId: 'cat-2',
    title: 'Banarasi Brocade Silk Nehru Jacket',
    slug: 'banarasi-brocade-silk-nehru-jacket',
    shortDescription: 'Handloom floral brocade sleeveless waist coat with mandarin collar.',
    description: 'Pair with kurtas or formal shirts for festive celebrations. Features antique brass buttons and chest pocket for pocket squares.',
    basePrice: 7999.00,
    salePrice: 6499.00,
    sku: 'SBJ-FASH-237',
    brand: 'Jitesh Couture',
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: true,
    rating: 4.7,
    reviews: 42,
    tags: ['ethnic', 'nehru-jacket', 'silk', 'banarasi'],
    imageUrl: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?q=80&w=1000',
    stock: 25,
  },
  {
    id: 'prod-238',
    categoryId: 'cat-2',
    title: 'Packable Down Feather Puffer Jacket',
    slug: 'packable-down-feather-puffer-jacket',
    shortDescription: '750-fill power ultra-light thermal puffer jacket with storage pouch.',
    description: 'Provides maximum warmth in sub-zero climates without weighing you down. Windproof nylon ripstop outer shell with fleece-lined handwarmer pockets.',
    basePrice: 8999.00,
    salePrice: 6999.00,
    sku: 'SBJ-FASH-238',
    brand: 'UrbanThread',
    isFeatured: false,
    isNewArrival: true,
    isBestSeller: false,
    rating: 4.6,
    reviews: 28,
    tags: ['puffer', 'jacket', 'winter', 'outerwear'],
    imageUrl: 'https://images.unsplash.com/photo-1544923246-77307dd654cb?q=80&w=1000',
    stock: 30,
  },
  {
    id: 'prod-239',
    categoryId: 'cat-2',
    title: 'Pleated Chiffon Evening Maxi Gown',
    slug: 'pleated-chiffon-evening-maxi-gown',
    shortDescription: 'Floor-length metallic ombre pleated gown with sweetheart neckline.',
    description: 'Make a graceful statement at gala events and receptions. Features concealed back zipper, soft satin lining, and flowing accordion pleats.',
    basePrice: 14999.00,
    salePrice: 11999.00,
    sku: 'SBJ-FASH-239',
    brand: 'Jitesh Couture',
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: false,
    rating: 4.8,
    reviews: 16,
    tags: ['gown', 'dress', 'eveningwear', 'fashion'],
    imageUrl: 'https://images.unsplash.com/photo-1566174053879-31528523f8ae?q=80&w=1000',
    stock: 12,
  },
  {
    id: 'prod-240',
    categoryId: 'cat-2',
    title: 'Casual Corduroy Button-Down Overshirt',
    slug: 'casual-corduroy-button-down-overshirt',
    shortDescription: '8-wale heavy cotton corduroy shirt jacket in vintage olive green.',
    description: 'Versatile layering piece for autumn and spring. Built with double chest flap pockets, tortoise buttons, and relaxed casual fit.',
    basePrice: 3999.00,
    salePrice: 2999.00,
    sku: 'SBJ-FASH-240',
    brand: 'UrbanThread',
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: true,
    rating: 4.7,
    reviews: 53,
    tags: ['corduroy', 'overshirt', 'jacket', 'casual'],
    imageUrl: 'https://images.unsplash.com/photo-1598032895397-b9472444bf93?q=80&w=1000',
    stock: 45,
  },
  {
    id: 'prod-241',
    categoryId: 'cat-2',
    title: 'Artisanal Terracotta Clay Bead Necklace Set',
    slug: 'artisanal-terracotta-clay-bead-necklace-set',
    shortDescription: 'Eco-friendly hand-painted clay jewelry set with matching drop earrings.',
    description: 'Handcrafted by traditional artisans using baked natural clay and non-toxic metallic pigment. Perfect companion for handloom sarees and kurtis.',
    basePrice: 1799.00,
    salePrice: null,
    sku: 'SBJ-FASH-241',
    brand: 'Jitesh Couture',
    isFeatured: false,
    isNewArrival: true,
    isBestSeller: false,
    rating: 4.6,
    reviews: 21,
    tags: ['jewelry', 'terracotta', 'ethnic', 'handcrafted'],
    imageUrl: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?q=80&w=1000',
    stock: 35,
  },
  {
    id: 'prod-242',
    categoryId: 'cat-2',
    title: 'Canvas Travel Duffle Bag with Leather Trim',
    slug: 'canvas-travel-duffle-bag-with-leather-trim',
    shortDescription: '45L heavy-duty waxed canvas weekender bag with shoe compartment.',
    description: 'Built for weekend getaways and gym sessions. Features thick full-grain leather straps, padded shoulder strap, and brass hardware.',
    basePrice: 5999.00,
    salePrice: 4699.00,
    sku: 'SBJ-FASH-242',
    brand: 'UrbanThread',
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: true,
    rating: 4.8,
    reviews: 79,
    tags: ['duffle', 'bag', 'travel', 'leather'],
    imageUrl: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?q=80&w=1000',
    stock: 40,
  },

  // ================= CATEGORY 3: HOME & LIVING (21 Products) =================
  {
    id: 'prod-243',
    categoryId: 'cat-3',
    title: 'Nordic Ceramic Sculptural Table Lamp',
    slug: 'nordic-ceramic-sculptural-table-lamp',
    shortDescription: 'Warm ambient ceramic table lamp with dimmable warm LED bulb & linen shade.',
    description: 'Elevate your living spaces with serene warm light. Crafted with textured off-white ceramic base and natural woven linen shade.',
    basePrice: 8999.00,
    salePrice: 7499.00,
    sku: 'SBJ-DECOR-404',
    brand: 'Lumina Living',
    isFeatured: true,
    isNewArrival: true,
    isBestSeller: true,
    rating: 4.7,
    reviews: 31,
    tags: ['lighting', 'lamp', 'decor', 'nordic'],
    imageUrl: 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?q=80&w=1000',
    stock: 25,
  },
  {
    id: 'prod-244',
    categoryId: 'cat-3',
    title: 'Hand-Carved Sheesham Wood Accent Armchair',
    slug: 'hand-carved-sheesham-wood-accent-armchair',
    shortDescription: 'Solid Indian rosewood armchair with natural rattan cane backrest.',
    description: 'Infuse vintage mid-century charm into your reading nook. Upholstered with high-density foam cushion wrapped in beige linen fabric.',
    basePrice: 24999.00,
    salePrice: 19999.00,
    sku: 'SBJ-HOME-244',
    brand: 'Solstice Home',
    isFeatured: true,
    isNewArrival: false,
    isBestSeller: true,
    rating: 4.9,
    reviews: 22,
    tags: ['chair', 'furniture', 'sheesham', 'decor'],
    imageUrl: 'https://images.unsplash.com/photo-1580481072645-022f9a6d83d0?q=80&w=1000',
    stock: 10,
  },
  {
    id: 'prod-245',
    categoryId: 'cat-3',
    title: 'Artisanal Fluted Ceramic Flower Vase',
    slug: 'artisanal-fluted-ceramic-flower-vase',
    shortDescription: 'Matte terracotta clay fluted vase for pampas grass & dry floral arrangements.',
    description: 'Hand-thrown by ceramic artists. Matte organic finish makes it a striking centerpiece for dining tables and mantlepieces.',
    basePrice: 2999.00,
    salePrice: 2299.00,
    sku: 'SBJ-HOME-245',
    brand: 'Lumina Living',
    isFeatured: false,
    isNewArrival: true,
    isBestSeller: true,
    rating: 4.8,
    reviews: 65,
    tags: ['vase', 'ceramic', 'decor', 'artisanal'],
    imageUrl: 'https://images.unsplash.com/photo-1612196808214-b7e239e5f6b7?q=80&w=1000',
    stock: 50,
  },
  {
    id: 'prod-246',
    categoryId: 'cat-3',
    title: 'Hand-Tufted 100% Wool Area Rug (5x7 ft)',
    slug: 'hand-tufted-100-wool-area-rug-5x7-ft',
    shortDescription: 'Geometric plush wool floor rug in warm beige & charcoal accents.',
    description: 'Super soft underfoot with natural sound dampening properties. Hand-tufted by skilled weavers using high-density New Zealand wool.',
    basePrice: 16999.00,
    salePrice: 13499.00,
    sku: 'SBJ-HOME-246',
    brand: 'Solstice Home',
    isFeatured: true,
    isNewArrival: false,
    isBestSeller: false,
    rating: 4.8,
    reviews: 19,
    tags: ['rug', 'carpet', 'wool', 'decor'],
    imageUrl: 'https://images.unsplash.com/photo-1600121848594-d8644e57abab?q=80&w=1000',
    stock: 15,
  },
  {
    id: 'prod-247',
    categoryId: 'cat-3',
    title: 'Japanese Cast Iron Teapot with Stainless Infuser',
    slug: 'japanese-cast-iron-teapot-with-stainless-infuser',
    shortDescription: '800ml enamel-lined tetsubin tea kettle with hobnail texture.',
    description: 'Retains heat evenly for the ultimate loose-leaf tea experience. Enamel coating prevents rust and preserves pure tea flavor.',
    basePrice: 4499.00,
    salePrice: 3499.00,
    sku: 'SBJ-HOME-247',
    brand: 'Lumina Living',
    isFeatured: false,
    isNewArrival: true,
    isBestSeller: true,
    rating: 4.9,
    reviews: 48,
    tags: ['teapot', 'kitchen', 'cast-iron', 'dining'],
    imageUrl: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?q=80&w=1000',
    stock: 35,
  },
  {
    id: 'prod-248',
    categoryId: 'cat-3',
    title: 'Organic Washed French Linen Bed Sheet Set',
    slug: 'organic-washed-french-linen-bed-sheet-set',
    shortDescription: '4-piece king bedsheet set with 2 pillow covers & fitted sheet.',
    description: 'Gets softer with every wash. Stone-washed 100% French flax linen keeps you cool in summer and warm in winter.',
    basePrice: 11999.00,
    salePrice: 9499.00,
    sku: 'SBJ-HOME-248',
    brand: 'Solstice Home',
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: true,
    rating: 4.7,
    reviews: 57,
    tags: ['bedsheet', 'linen', 'bedding', 'home'],
    imageUrl: 'https://images.unsplash.com/photo-1616046229478-9901c5536a45?q=80&w=1000',
    stock: 30,
  },
  {
    id: 'prod-249',
    categoryId: 'cat-3',
    title: 'Solid Brass Minimalist Wall Clock (12-inch)',
    slug: 'solid-brass-minimalist-wall-clock-12inch',
    shortDescription: 'Silent quartz movement clock with brushed brass frame & glass lens.',
    description: 'Timeless wall accent for modern living rooms and home offices. Features non-ticking sweep second hand mechanism.',
    basePrice: 3999.00,
    salePrice: 2999.00,
    sku: 'SBJ-HOME-249',
    brand: 'Lumina Living',
    isFeatured: false,
    isNewArrival: true,
    isBestSeller: false,
    rating: 4.6,
    reviews: 32,
    tags: ['clock', 'brass', 'wall-decor', 'decor'],
    imageUrl: 'https://images.unsplash.com/photo-1563861826100-9cb868fdbe1c?q=80&w=1000',
    stock: 40,
  },
  {
    id: 'prod-250',
    categoryId: 'cat-3',
    title: 'Tri-Ply Stainless Steel Cookware Set (5 Pcs)',
    slug: 'tri-ply-stainless-steel-cookware-set-5-pcs',
    shortDescription: 'Induction-compatible heavy bottom pots & pans with tempered glass lids.',
    description: 'Aluminum core sandwiched between food-grade 304 stainless steel ensures 100% uniform heat distribution without hot spots.',
    basePrice: 14999.00,
    salePrice: 11999.00,
    sku: 'SBJ-HOME-250',
    brand: 'Solstice Home',
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: true,
    rating: 4.8,
    reviews: 74,
    tags: ['cookware', 'kitchen', 'stainless-steel', 'pots'],
    imageUrl: 'https://images.unsplash.com/photo-1584992236310-6edddc08acff?q=80&w=1000',
    stock: 25,
  },
  {
    id: 'prod-251',
    categoryId: 'cat-3',
    title: 'Hand-Woven Natural Jute Storage Baskets (Set of 3)',
    slug: 'hand-woven-natural-jute-storage-baskets-set-of-3',
    shortDescription: 'Eco-friendly collapsible laundry & toy organizer bins with leather handles.',
    description: 'Organize clutter naturally. Woven from sustainably harvested natural jute fibers with cotton fabric lining.',
    basePrice: 2499.00,
    salePrice: 1899.00,
    sku: 'SBJ-HOME-251',
    brand: 'Lumina Living',
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: true,
    rating: 4.7,
    reviews: 86,
    tags: ['baskets', 'jute', 'storage', 'organizer'],
    imageUrl: 'https://images.unsplash.com/photo-1616627547584-bf28cee262db?q=80&w=1000',
    stock: 60,
  },
  {
    id: 'prod-252',
    categoryId: 'cat-3',
    title: 'Aroma Diffuser & Ultrasonic Humidifier',
    slug: 'aroma-diffuser-ultrasonic-humidifier',
    shortDescription: '500ml faux wood grain essential oil diffuser with 7-color LED lighting.',
    description: 'Purify room air while diffusing calming essential oil scents. Includes automatic safety shut-off and whisper-quiet operation under 25dB.',
    basePrice: 3499.00,
    salePrice: 2499.00,
    sku: 'SBJ-HOME-252',
    brand: 'Lumina Living',
    isFeatured: false,
    isNewArrival: true,
    isBestSeller: false,
    rating: 4.6,
    reviews: 53,
    tags: ['diffuser', 'aromatherapy', 'home', 'wellness'],
    imageUrl: 'https://images.unsplash.com/photo-1602928321679-560b4139c901?q=80&w=1000',
    stock: 50,
  },
  {
    id: 'prod-253',
    categoryId: 'cat-3',
    title: 'Handcrafted Marble & Acacia Wood Serving Board',
    slug: 'handcrafted-marble-acacia-wood-serving-board',
    shortDescription: 'Charcuterie & cheese platter board with brass inlay strip.',
    description: 'Impress guests at wine & cheese evenings. Cool white Agra marble combined with warm solid acacia wood.',
    basePrice: 2999.00,
    salePrice: null,
    sku: 'SBJ-HOME-253',
    brand: 'Solstice Home',
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: true,
    rating: 4.9,
    reviews: 41,
    tags: ['serving-board', 'kitchen', 'marble', 'dining'],
    imageUrl: 'https://images.unsplash.com/photo-1590794056226-79ef3a8147e1?q=80&w=1000',
    stock: 35,
  },
  {
    id: 'prod-254',
    categoryId: 'cat-3',
    title: 'Abstract Botanical Framed Canvas Art (Set of 2)',
    slug: 'abstract-botanical-framed-canvas-art-set-of-2',
    shortDescription: '24x36 inch museum-grade giclee prints in natural oak frames.',
    description: 'Add sophisticated botanical colors to living room walls. Printed on heavy 350 GSM cotton canvas with fade-resistant pigment inks.',
    basePrice: 7999.00,
    salePrice: 5999.00,
    sku: 'SBJ-HOME-254',
    brand: 'Lumina Living',
    isFeatured: false,
    isNewArrival: true,
    isBestSeller: false,
    rating: 4.7,
    reviews: 21,
    tags: ['art', 'wall-decor', 'canvas', 'home'],
    imageUrl: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?q=80&w=1000',
    stock: 20,
  },
  {
    id: 'prod-255',
    categoryId: 'cat-3',
    title: 'Hand-Knitted Cotton Cable Throw Blanket',
    slug: 'hand-knitted-cotton-cable-throw-blanket',
    shortDescription: '50x60 inch heavy cable knit sofa throw blanket in soft oat cream.',
    description: 'Snuggle up on chilly evenings. Knitted from 100% natural breathable cotton yarn with plush tassel fringes.',
    basePrice: 4999.00,
    salePrice: 3799.00,
    sku: 'SBJ-HOME-255',
    brand: 'Solstice Home',
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: true,
    rating: 4.8,
    reviews: 63,
    tags: ['blanket', 'throw', 'cotton', 'decor'],
    imageUrl: 'https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?q=80&w=1000',
    stock: 45,
  },
  {
    id: 'prod-256',
    categoryId: 'cat-3',
    title: 'Solid Mango Wood Nesting Coffee Tables',
    slug: 'solid-mango-wood-nesting-coffee-tables',
    shortDescription: 'Set of 2 round nesting accent tables with black powder-coated iron legs.',
    description: 'Flexible living room furniture solution. Top surface finished with clear protective lacquer to highlight natural wood grain.',
    basePrice: 15999.00,
    salePrice: 12999.00,
    sku: 'SBJ-HOME-256',
    brand: 'Solstice Home',
    isFeatured: true,
    isNewArrival: false,
    isBestSeller: false,
    rating: 4.8,
    reviews: 17,
    tags: ['tables', 'furniture', 'wood', 'living-room'],
    imageUrl: 'https://images.unsplash.com/photo-1533090161767-e6ffed986c88?q=80&w=1000',
    stock: 12,
  },
  {
    id: 'prod-257',
    categoryId: 'cat-3',
    title: 'Scented Soy Wax Candle in Ceramic Vessel',
    slug: 'scented-soy-wax-candle-in-ceramic-vessel',
    shortDescription: '300g hand-poured candle with amber & sandalwood essential oils (60h burn time).',
    description: 'Transform home atmosphere with warm woody aromas. Clean-burning 100% soy wax with double cotton wicks.',
    basePrice: 1999.00,
    salePrice: 1499.00,
    sku: 'SBJ-HOME-257',
    brand: 'Lumina Living',
    isFeatured: false,
    isNewArrival: true,
    isBestSeller: true,
    rating: 4.9,
    reviews: 94,
    tags: ['candle', 'scented', 'decor', 'aroma'],
    imageUrl: 'https://images.unsplash.com/photo-1603006905003-be475563bc59?q=80&w=1000',
    stock: 75,
  },
  {
    id: 'prod-258',
    categoryId: 'cat-3',
    title: 'Handblown Crystal Wine Decanter (1500ml)',
    slug: 'handblown-crystal-wine-decanter-1500ml',
    shortDescription: 'Lead-free crystal aerator carafe with slanted pour spout.',
    description: 'Enhance wine flavor and aroma before serving. Ergonomic shape provides easy handling and spill-free pouring.',
    basePrice: 3499.00,
    salePrice: null,
    sku: 'SBJ-HOME-258',
    brand: 'Lumina Living',
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: false,
    rating: 4.7,
    reviews: 23,
    tags: ['decanter', 'crystal', 'dining', 'barware'],
    imageUrl: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?q=80&w=1000',
    stock: 25,
  },
  {
    id: 'prod-259',
    categoryId: 'cat-3',
    title: 'Luxury Egyptian Cotton Bath Towels (Set of 4)',
    slug: 'luxury-egyptian-cotton-bath-towels-set-of-4',
    shortDescription: '700 GSM plush absorbent bath towels in slate grey.',
    description: 'Experience hotel-grade spa comfort at home. Long-staple combed Egyptian cotton provides high absorbency and fast drying.',
    basePrice: 4999.00,
    salePrice: 3799.00,
    sku: 'SBJ-HOME-259',
    brand: 'Solstice Home',
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: true,
    rating: 4.8,
    reviews: 68,
    tags: ['towels', 'bath', 'cotton', 'luxury'],
    imageUrl: 'https://images.unsplash.com/photo-1616627547584-bf28cee262db?q=80&w=1000',
    stock: 50,
  },
  {
    id: 'prod-260',
    categoryId: 'cat-3',
    title: 'Handmade Hammered Copper Water Pitcher (1.5L)',
    slug: 'handmade-hammered-copper-water-pitcher-15l',
    shortDescription: 'Pure Ayurvedic copper jug with brass handle & spill-proof lid.',
    description: 'Promote wellness according to traditional Ayurvedic practices. Hand-hammered by copper artisans in Rajasthan.',
    basePrice: 2799.00,
    salePrice: 2199.00,
    sku: 'SBJ-HOME-260',
    brand: 'Solstice Home',
    isFeatured: false,
    isNewArrival: true,
    isBestSeller: true,
    rating: 4.8,
    reviews: 52,
    tags: ['copper', 'ayurveda', 'kitchen', 'dining'],
    imageUrl: 'https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?q=80&w=1000',
    stock: 40,
  },
  {
    id: 'prod-261',
    categoryId: 'cat-3',
    title: 'Rattan Cane Counter Height Bar Stool',
    slug: 'rattan-cane-counter-height-bar-stool',
    shortDescription: 'Solid teak wood stool with natural woven cane seat & footrest.',
    description: 'Perfect accent seating for kitchen islands and breakfast counters. Sealed with protective matte coat for easy wipe cleaning.',
    basePrice: 8999.00,
    salePrice: 6999.00,
    sku: 'SBJ-HOME-261',
    brand: 'Solstice Home',
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: false,
    rating: 4.6,
    reviews: 15,
    tags: ['stool', 'rattan', 'furniture', 'kitchen'],
    imageUrl: 'https://images.unsplash.com/photo-1503602642458-232111445657?q=80&w=1000',
    stock: 16,
  },
  {
    id: 'prod-262',
    categoryId: 'cat-3',
    title: 'Bamboomesh Ergonomic Desk Footrest Pillow',
    slug: 'bamboomesh-ergonomic-desk-footrest-pillow',
    shortDescription: 'High-density memory foam foot rest with washable bamboo charcoal cover.',
    description: 'Relieve lower back stress while working long hours. Ergonomic teardrop curve supports natural foot placement under desk.',
    basePrice: 1999.00,
    salePrice: 1499.00,
    sku: 'SBJ-HOME-262',
    brand: 'Lumina Living',
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: true,
    rating: 4.7,
    reviews: 81,
    tags: ['footrest', 'ergonomic', 'office', 'home'],
    imageUrl: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?q=80&w=1000',
    stock: 65,
  },

  // ================= CATEGORY 4: TIMEPIECES & ACCESSORIES (21 Products) =================
  {
    id: 'prod-263',
    categoryId: 'cat-4',
    title: 'Vanguard Automatic GMT Chronograph Watch',
    slug: 'vanguard-automatic-gmt-chronograph-watch',
    shortDescription: 'Swiss-inspired automatic movement with dual time zone bezel and sapphire crystal.',
    description: 'The Vanguard Automatic GMT is crafted for global travelers. Features 200m water resistance, exhibition caseback, and 316L stainless steel bracelet.',
    basePrice: 48999.00,
    salePrice: 42500.00,
    sku: 'SBJ-WATCH-202',
    brand: 'Vanguard Horology',
    isFeatured: true,
    isNewArrival: true,
    isBestSeller: true,
    rating: 4.9,
    reviews: 42,
    tags: ['watch', 'automatic', 'gmt', 'luxury'],
    imageUrl: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?q=80&w=1000',
    stock: 15,
  },
  {
    id: 'prod-264',
    categoryId: 'cat-4',
    title: 'AeroPilot Mechanical Skeleton Watch',
    slug: 'aeropilot-mechanical-skeleton-watch',
    shortDescription: 'Open-heart skeleton movement watch with Italian vintage leather strap.',
    description: 'Marvel at the mechanical heartbeat inside. Features gunmetal PVD case, luminous hands, and anti-reflective sapphire glass.',
    basePrice: 32999.00,
    salePrice: 26999.00,
    sku: 'SBJ-TIME-264',
    brand: 'Vanguard Horology',
    isFeatured: true,
    isNewArrival: true,
    isBestSeller: false,
    rating: 4.8,
    reviews: 28,
    tags: ['watch', 'skeleton', 'mechanical', 'leather'],
    imageUrl: 'https://images.unsplash.com/photo-1524805444758-089113d48a6d?q=80&w=1000',
    stock: 18,
  },
  {
    id: 'prod-265',
    categoryId: 'cat-4',
    title: 'Heritage Minimalist Quartz Dress Watch',
    slug: 'heritage-minimalist-quartz-dress-watch',
    shortDescription: 'Ultra-thin 6.5mm rose gold case watch with genuine alligator grain strap.',
    description: 'Subtle luxury for formal attire. Features clean sunray dial, Japanese quartz precision caliber, and scratch-resistant sapphire crystal.',
    basePrice: 14999.00,
    salePrice: 11999.00,
    sku: 'SBJ-TIME-265',
    brand: 'Vanguard Horology',
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: true,
    rating: 4.7,
    reviews: 61,
    tags: ['watch', 'quartz', 'minimalist', 'dress'],
    imageUrl: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?q=80&w=1000',
    stock: 30,
  },
  {
    id: 'prod-266',
    categoryId: 'cat-4',
    title: 'Full-Grain Italian Leather Bi-Fold Wallet',
    slug: 'full-grain-italian-leather-bifold-wallet',
    shortDescription: 'Hand-stitched vegetable-tanned leather wallet with RFID blocking lining.',
    description: 'Slim profile wallet holding up to 10 cards, cash compartment, and quick-access ID window. Develops a rich natural patina over time.',
    basePrice: 3499.00,
    salePrice: 2699.00,
    sku: 'SBJ-TIME-266',
    brand: 'Chronos Craft',
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: true,
    rating: 4.9,
    reviews: 104,
    tags: ['wallet', 'leather', 'rfid', 'accessories'],
    imageUrl: 'https://images.unsplash.com/photo-1627123424574-724758594e93?q=80&w=1000',
    stock: 75,
  },
  {
    id: 'prod-267',
    categoryId: 'cat-4',
    title: 'Polarized Titanium Aviator Sunglasses',
    slug: 'polarized-titanium-aviator-sunglasses',
    shortDescription: 'Ultra-lightweight aerospace titanium sunglasses with 100% UV400 lenses.',
    description: 'Engineered for glare-free vision. Features anti-reflective lens coating, adjustable silicone nose pads, and protective hard leather case.',
    basePrice: 7999.00,
    salePrice: 5999.00,
    sku: 'SBJ-TIME-267',
    brand: 'Chronos Craft',
    isFeatured: true,
    isNewArrival: true,
    isBestSeller: true,
    rating: 4.8,
    reviews: 45,
    tags: ['sunglasses', 'titanium', 'polarized', 'eyewear'],
    imageUrl: 'https://images.unsplash.com/photo-1511499767150-a48a237f0083?q=80&w=1000',
    stock: 40,
  },
  {
    id: 'prod-268',
    categoryId: 'cat-4',
    title: 'Sterling Silver 925 Cuban Link Chain (22-inch)',
    slug: 'sterling-silver-925-cuban-link-chain-22inch',
    shortDescription: 'Solid 925 sterling silver diamond-cut bevelled Cuban neck chain.',
    description: 'High-polish rhodium plating prevents tarnishing. Features durable lobster claw clasp and authentic 925 hallmark stamp.',
    basePrice: 9999.00,
    salePrice: 7999.00,
    sku: 'SBJ-TIME-268',
    brand: 'Chronos Craft',
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: true,
    rating: 4.8,
    reviews: 58,
    tags: ['chain', 'silver', 'jewelry', 'menswear'],
    imageUrl: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?q=80&w=1000',
    stock: 25,
  },
  {
    id: 'prod-269',
    categoryId: 'cat-4',
    title: 'Reversible Italian Calfskin Leather Belt',
    slug: 'reversible-italian-calfskin-leather-belt',
    shortDescription: 'Dual-sided black & cognac brown formal belt with twist buckle.',
    description: 'Two versatile looks in one premium belt. Made from 35mm wide full-grain Italian leather with hand-finished edges.',
    basePrice: 3999.00,
    salePrice: 2999.00,
    sku: 'SBJ-TIME-269',
    brand: 'Chronos Craft',
    isFeatured: false,
    isNewArrival: true,
    isBestSeller: true,
    rating: 4.7,
    reviews: 73,
    tags: ['belt', 'leather', 'accessories', 'formal'],
    imageUrl: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?q=80&w=1000',
    stock: 50,
  },
  {
    id: 'prod-270',
    categoryId: 'cat-4',
    title: 'OceanDiver 300M Professional Automatic Watch',
    slug: 'oceandiver-300m-professional-automatic-watch',
    shortDescription: '300m water resistant diver watch with ceramic bezel & Super-LumiNova.',
    description: 'Built for oceanic exploration. Features helium escape valve, unidirectional 120-click ceramic bezel, and heavy stainless steel bracelet.',
    basePrice: 42999.00,
    salePrice: 35999.00,
    sku: 'SBJ-TIME-270',
    brand: 'Vanguard Horology',
    isFeatured: true,
    isNewArrival: false,
    isBestSeller: false,
    rating: 4.9,
    reviews: 31,
    tags: ['watch', 'diver', 'automatic', 'waterproof'],
    imageUrl: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?q=80&w=1000',
    stock: 12,
  },
  {
    id: 'prod-271',
    categoryId: 'cat-4',
    title: 'Vintage Brass Compass Cufflinks Set',
    slug: 'vintage-brass-compass-cufflinks-set',
    shortDescription: 'Functional mini working compass shirt cufflinks in velvet gift box.',
    description: 'Conversation starter for suit lovers. Features working magnetic compasses encased under durable dome glass.',
    basePrice: 2499.00,
    salePrice: 1899.00,
    sku: 'SBJ-TIME-271',
    brand: 'Chronos Craft',
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: false,
    rating: 4.6,
    reviews: 19,
    tags: ['cufflinks', 'formal', 'accessories', 'gift'],
    imageUrl: 'https://images.unsplash.com/photo-1617038260897-41a1f14a8ca0?q=80&w=1000',
    stock: 30,
  },
  {
    id: 'prod-272',
    categoryId: 'cat-4',
    title: 'Top-Grain Leather Watch Travel Roll (3 Slots)',
    slug: 'top-grain-leather-watch-travel-roll-3-slots',
    shortDescription: 'Handcrafted leather watch organizer case with removable cushions.',
    description: 'Keep your favorite watches protected while traveling. Features soft micro-suede interior lining and secure brass snap buttons.',
    basePrice: 4499.00,
    salePrice: 3499.00,
    sku: 'SBJ-TIME-272',
    brand: 'Chronos Craft',
    isFeatured: false,
    isNewArrival: true,
    isBestSeller: true,
    rating: 4.8,
    reviews: 42,
    tags: ['watch-roll', 'travel', 'leather', 'case'],
    imageUrl: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?q=80&w=1000',
    stock: 35,
  },
  {
    id: 'prod-273',
    categoryId: 'cat-4',
    title: 'Handcrafted Braided Leather Bracelet with Magnetic Clasp',
    slug: 'handcrafted-braided-leather-bracelet-with-magnetic-clasp',
    shortDescription: 'Genuine double-wrapped woven leather wristband with brushed steel clasp.',
    description: 'Rugged yet refined wrist accessory. Made from supple Italian leather rope secured by strong neodymium magnetic closure.',
    basePrice: 1999.00,
    salePrice: 1499.00,
    sku: 'SBJ-TIME-273',
    brand: 'Chronos Craft',
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: true,
    rating: 4.7,
    reviews: 89,
    tags: ['bracelet', 'leather', 'jewelry', 'menswear'],
    imageUrl: 'https://images.unsplash.com/photo-1611591475143-4f8a753715db?q=80&w=1000',
    stock: 60,
  },
  {
    id: 'prod-274',
    categoryId: 'cat-4',
    title: 'Handmade Acetate Square Optical Glasses',
    slug: 'handmade-acetate-square-optical-glasses',
    shortDescription: 'Mazzucchelli Italian acetate eyeglass frames with blue light filter lenses.',
    description: 'Combine vintage aesthetics with digital eye protection. Features 5-barrel German hinges and clear anti-blue light coating.',
    basePrice: 5999.00,
    salePrice: 4499.00,
    sku: 'SBJ-TIME-274',
    brand: 'Chronos Craft',
    isFeatured: false,
    isNewArrival: true,
    isBestSeller: false,
    rating: 4.6,
    reviews: 26,
    tags: ['glasses', 'eyewear', 'blue-light', 'acetate'],
    imageUrl: 'https://images.unsplash.com/photo-1591076482161-42ce6da69f67?q=80&w=1000',
    stock: 25,
  },
  {
    id: 'prod-275',
    categoryId: 'cat-4',
    title: 'Chronograph Solar Powered Tachymeter Watch',
    slug: 'chronograph-solar-powered-tachymeter-watch',
    shortDescription: 'Eco-drive solar movement watch requiring no battery replacement.',
    description: 'Charges under any natural or indoor light source. Features 1/20th second stopwatch chronograph sub-dials and tachymeter bezel.',
    basePrice: 28999.00,
    salePrice: 23999.00,
    sku: 'SBJ-TIME-275',
    brand: 'Vanguard Horology',
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: true,
    rating: 4.8,
    reviews: 37,
    tags: ['watch', 'solar', 'chronograph', 'tech'],
    imageUrl: 'https://images.unsplash.com/photo-1542496658-e33a6d0d50f6?q=80&w=1000',
    stock: 16,
  },
  {
    id: 'prod-276',
    categoryId: 'cat-4',
    title: 'Solid Brass Money Clip & Card Holder',
    slug: 'solid-brass-money-clip-card-holder',
    shortDescription: 'Compact spring-loaded brass clip holding up to 15 bills & 5 cards.',
    description: 'Ditch pocket bulk. Machined from solid aircraft-grade brass that oxidizes into a rich vintage patina.',
    basePrice: 1799.00,
    salePrice: 1299.00,
    sku: 'SBJ-TIME-276',
    brand: 'Chronos Craft',
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: false,
    rating: 4.5,
    reviews: 40,
    tags: ['money-clip', 'brass', 'wallet', 'minimalist'],
    imageUrl: 'https://images.unsplash.com/photo-1627123424574-724758594e93?q=80&w=1000',
    stock: 50,
  },
  {
    id: 'prod-277',
    categoryId: 'cat-4',
    title: 'Natural Black Onyx Stone Signet Ring',
    slug: 'natural-black-onyx-stone-signet-ring',
    shortDescription: '925 sterling silver signet ring with genuine oval onyx stone.',
    description: 'Statement jewelry piece crafted with bold masculine presence. Hand-polished solid silver band with smooth black onyx center.',
    basePrice: 3999.00,
    salePrice: 2999.00,
    sku: 'SBJ-TIME-277',
    brand: 'Chronos Craft',
    isFeatured: false,
    isNewArrival: true,
    isBestSeller: false,
    rating: 4.7,
    reviews: 29,
    tags: ['ring', 'onyx', 'silver', 'jewelry'],
    imageUrl: 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?q=80&w=1000',
    stock: 30,
  },
  {
    id: 'prod-278',
    categoryId: 'cat-4',
    title: 'Vintage Leather Key Organizer Keychain',
    slug: 'vintage-leather-key-organizer-keychain',
    shortDescription: 'Compact locking keyholder preventing key jingle for up to 8 keys.',
    description: 'Eliminate key scratches on your phone screen. Crafted from vegetable-tanned leather with stainless steel locking screw.',
    basePrice: 1499.00,
    salePrice: 999.00,
    sku: 'SBJ-TIME-278',
    brand: 'Chronos Craft',
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: true,
    rating: 4.8,
    reviews: 115,
    tags: ['keychain', 'leather', 'organizer', 'accessories'],
    imageUrl: 'https://images.unsplash.com/photo-1612817288484-6f916006741a?q=80&w=1000',
    stock: 90,
  },
  {
    id: 'prod-279',
    categoryId: 'cat-4',
    title: 'Classic Moonphase Calendar Quartz Watch',
    slug: 'classic-moonphase-calendar-quartz-watch',
    shortDescription: 'Complication watch displaying lunar phase, day, date & month sub-dials.',
    description: 'Astronomical watchmaking artistry. Features deep blue starry dial, silver index markers, and genuine navy leather strap.',
    basePrice: 19999.00,
    salePrice: 15999.00,
    sku: 'SBJ-TIME-279',
    brand: 'Vanguard Horology',
    isFeatured: false,
    isNewArrival: true,
    isBestSeller: false,
    rating: 4.8,
    reviews: 22,
    tags: ['watch', 'moonphase', 'quartz', 'calendar'],
    imageUrl: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?q=80&w=1000',
    stock: 20,
  },
  {
    id: 'prod-280',
    categoryId: 'cat-4',
    title: 'Leather Desk Valet Tray for Everyday Carry',
    slug: 'leather-desk-valet-tray-for-everyday-carry',
    shortDescription: 'Corner-snap leather catchall tray for keys, watch, coins & wallet.',
    description: 'Keep your nightstand or entryway organized. Flat-packing design snaps together quickly using brass rivets.',
    basePrice: 2299.00,
    salePrice: 1699.00,
    sku: 'SBJ-TIME-280',
    brand: 'Chronos Craft',
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: true,
    rating: 4.9,
    reviews: 64,
    tags: ['valet-tray', 'leather', 'edc', 'organizer'],
    imageUrl: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?q=80&w=1000',
    stock: 45,
  },
  {
    id: 'prod-281',
    categoryId: 'cat-4',
    title: 'Titanium Smart Ring for Sleep & Fitness Tracking',
    slug: 'titanium-smart-ring-for-sleep-fitness-tracking',
    shortDescription: 'Waterproof smart ring with body temperature & heart rate variability sensor.',
    description: 'Screenless health monitoring that fits comfortably on your finger. 7-day battery life with wireless charging case.',
    basePrice: 21999.00,
    salePrice: 17999.00,
    sku: 'SBJ-TIME-281',
    brand: 'Vanguard Horology',
    isFeatured: true,
    isNewArrival: true,
    isBestSeller: false,
    rating: 4.7,
    reviews: 35,
    tags: ['smart-ring', 'wearable', 'titanium', 'fitness'],
    imageUrl: 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?q=80&w=1000',
    stock: 25,
  },
  {
    id: 'prod-282',
    categoryId: 'cat-4',
    title: 'Hand-Carved Wooden Watch Winder (Single)',
    slug: 'hand-carved-wooden-watch-winder-single',
    shortDescription: 'Ultra-silent Japanese Mabuchi motor watch winder in walnut finish.',
    description: 'Keep your automatic watches wound and accurate when not on wrist. Features 4 rotation mode settings and soft velvet pillow.',
    basePrice: 7999.00,
    salePrice: 5999.00,
    sku: 'SBJ-TIME-282',
    brand: 'Vanguard Horology',
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: false,
    rating: 4.8,
    reviews: 19,
    tags: ['watch-winder', 'automatic', 'wood', 'accessories'],
    imageUrl: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?q=80&w=1000',
    stock: 15,
  },
  {
    id: 'prod-283',
    categoryId: 'cat-4',
    title: 'Luxury Saffiano Leather Passport Cover Holder',
    slug: 'luxury-saffiano-leather-passport-cover-holder',
    shortDescription: 'Scratch-resistant leather passport sleeve with boarding pass slot.',
    description: 'Travel in style while keeping passports and travel documents safe. Includes 4 credit card slots and cash pocket.',
    basePrice: 2499.00,
    salePrice: 1799.00,
    sku: 'SBJ-TIME-283',
    brand: 'Chronos Craft',
    isFeatured: false,
    isNewArrival: true,
    isBestSeller: true,
    rating: 4.8,
    reviews: 52,
    tags: ['passport-holder', 'travel', 'leather', 'saffiano'],
    imageUrl: 'https://images.unsplash.com/photo-1544816155-12df9643f363?q=80&w=1000',
    stock: 50,
  },

  // ================= CATEGORY 5: BEAUTY & WELLNESS (21 Products) =================
  {
    id: 'prod-284',
    categoryId: 'cat-5',
    title: 'Botanical Elixir Facial Serum & Rose Quartz Roller',
    slug: 'botanical-elixir-facial-serum-rose-quartz-roller',
    shortDescription: 'Cold-pressed organic rosehip & saffron oil infused serum with rose quartz applicator.',
    description: 'Rejuvenate your skin with 100% pure cold-pressed botanical oils. Hydrates deeply, reduces fine lines, and restores youthful radiance.',
    basePrice: 4499.00,
    salePrice: 3899.00,
    sku: 'SBJ-SKIN-505',
    brand: 'Aetheria Botanicals',
    isFeatured: true,
    isNewArrival: true,
    isBestSeller: true,
    rating: 4.9,
    reviews: 74,
    tags: ['skincare', 'serum', 'organic', 'botanical'],
    imageUrl: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?q=80&w=1000',
    stock: 45,
  },
  {
    id: 'prod-285',
    categoryId: 'cat-5',
    title: 'Hydrating Hyaluronic Acid & Niacinamide Day Cream',
    slug: 'hydrating-hyaluronic-acid-niacinamide-day-cream',
    shortDescription: 'Lightweight gel-moisturizer with 2% Niacinamide & SPF 30 protection.',
    description: 'Provides 48-hour continuous hydration without clogging pores. Strengthens skin barrier and minimizes visible pore appearance.',
    basePrice: 2499.00,
    salePrice: 1899.00,
    sku: 'SBJ-WELL-285',
    brand: 'PureVita',
    isFeatured: true,
    isNewArrival: true,
    isBestSeller: true,
    rating: 4.8,
    reviews: 92,
    tags: ['skincare', 'moisturizer', 'niacinamide', 'spf'],
    imageUrl: 'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?q=80&w=1000',
    stock: 80,
  },
  {
    id: 'prod-286',
    categoryId: 'cat-5',
    title: 'Vitamin C Brightening Facial Night Mask (50g)',
    slug: 'vitamin-c-brightening-facial-night-mask-50g',
    shortDescription: 'Overnight repair sleeping mask with 15% L-Ascorbic Acid & Kakadu Plum.',
    description: 'Wake up to glowing radiant skin. Fades dark spots, evens skin tone, and boosts collagen synthesis overnight.',
    basePrice: 2999.00,
    salePrice: 2299.00,
    sku: 'SBJ-WELL-286',
    brand: 'Aetheria Botanicals',
    isFeatured: false,
    isNewArrival: true,
    isBestSeller: false,
    rating: 4.7,
    reviews: 39,
    tags: ['skincare', 'vitamin-c', 'night-mask', 'glowing'],
    imageUrl: 'https://images.unsplash.com/photo-1567928269937-aec41455b77a?q=80&w=1000',
    stock: 40,
  },
  {
    id: 'prod-287',
    categoryId: 'cat-5',
    title: 'Artisanal Organic Lavender & Chamomile Bath Salts',
    slug: 'artisanal-organic-lavender-chamomile-bath-salts',
    shortDescription: '450g Dead Sea bath soak with dried lavender buds & essential oils.',
    description: 'Relieve muscle tension and unwind after stressful days. Mineral-rich salts detoxify skin while relaxing mind and body.',
    basePrice: 1499.00,
    salePrice: 999.00,
    sku: 'SBJ-WELL-287',
    brand: 'PureVita',
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: true,
    rating: 4.8,
    reviews: 67,
    tags: ['bath-salts', 'spa', 'lavender', 'relaxation'],
    imageUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?q=80&w=1000',
    stock: 65,
  },
  {
    id: 'prod-288',
    categoryId: 'cat-5',
    title: 'Cold-Pressed Kashmiri Kumkumadi Tailam Facial Oil',
    slug: 'cold-pressed-kashmiri-kumkumadi-tailam-facial-oil',
    shortDescription: 'Ayurvedic night beauty elixir infused with pure saffron strands & goat milk.',
    description: 'Authentic 26-herb Ayurvedic formulation. Promotes complexion brightening, reduces pigmentation, and smoothes fine lines.',
    basePrice: 3999.00,
    salePrice: 3299.00,
    sku: 'SBJ-WELL-288',
    brand: 'Aetheria Botanicals',
    isFeatured: true,
    isNewArrival: false,
    isBestSeller: true,
    rating: 4.9,
    reviews: 58,
    tags: ['ayurveda', 'kumkumadi', 'facial-oil', 'saffron'],
    imageUrl: 'https://images.unsplash.com/photo-1608248597261-833258657640?q=80&w=1000',
    stock: 30,
  },
  {
    id: 'prod-289',
    categoryId: 'cat-5',
    title: 'Artisanal Loose-Leaf Darjeeling First Flush Black Tea',
    slug: 'artisanal-loose-leaf-darjeeling-first-flush-black-tea',
    shortDescription: '250g tin of single-estate spring harvest organic black tea leaves.',
    description: 'Known as the Champagne of teas. Features delicate floral aroma, muscatel notes, and light golden amber liquor.',
    basePrice: 2499.00,
    salePrice: null,
    sku: 'SBJ-WELL-289',
    brand: 'PureVita',
    isFeatured: false,
    isNewArrival: true,
    isBestSeller: true,
    rating: 4.9,
    reviews: 43,
    tags: ['tea', 'darjeeling', 'organic', 'gourmet'],
    imageUrl: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?q=80&w=1000',
    stock: 50,
  },
  {
    id: 'prod-290',
    categoryId: 'cat-5',
    title: 'Natural Charcoal Cleansing Exfoliating Scrub',
    slug: 'natural-charcoal-cleansing-exfoliating-scrub',
    shortDescription: 'Deep pore detox face scrub with activated bamboo charcoal & walnut shell particles.',
    description: 'Draw out deep impurities, excess sebum, and dead skin cells. Infused with tea tree oil to prevent acne breakouts.',
    basePrice: 1299.00,
    salePrice: 899.00,
    sku: 'SBJ-WELL-290',
    brand: 'PureVita',
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: true,
    rating: 4.6,
    reviews: 82,
    tags: ['scrub', 'charcoal', 'skincare', 'exfoliator'],
    imageUrl: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?q=80&w=1000',
    stock: 70,
  },
  {
    id: 'prod-291',
    categoryId: 'cat-5',
    title: 'Pure Organic Bhringraj Hair Growth Oil (200ml)',
    slug: 'pure-organic-bhringraj-hair-growth-oil-200ml',
    shortDescription: 'Traditional sesame oil decoction with Bhringraj, Amla & Brahmi herbs.',
    description: 'Nourishes scalp from roots to tips. Reduces hair fall, prevents premature greying, and restores hair thickness naturally.',
    basePrice: 1799.00,
    salePrice: 1299.00,
    sku: 'SBJ-WELL-291',
    brand: 'Aetheria Botanicals',
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: true,
    rating: 4.8,
    reviews: 110,
    tags: ['hair-care', 'bhringraj', 'ayurveda', 'hair-oil'],
    imageUrl: 'https://images.unsplash.com/photo-1608248597261-833258657640?q=80&w=1000',
    stock: 85,
  },
  {
    id: 'prod-292',
    categoryId: 'cat-5',
    title: 'Rosewater & Aloe Vera Gentle Hydrating Toner',
    slug: 'rosewater-aloe-vera-gentle-hydrating-toner',
    shortDescription: 'Alcohol-free facial mist made from pure Kannauj steam-distilled damask roses.',
    description: 'Instantly refreshes and balances skin pH. Tightens pores while soothing skin redness and irritation.',
    basePrice: 1199.00,
    salePrice: 849.00,
    sku: 'SBJ-WELL-292',
    brand: 'Aetheria Botanicals',
    isFeatured: false,
    isNewArrival: true,
    isBestSeller: false,
    rating: 4.7,
    reviews: 54,
    tags: ['toner', 'rosewater', 'skincare', 'mist'],
    imageUrl: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?q=80&w=1000',
    stock: 60,
  },
  {
    id: 'prod-293',
    categoryId: 'cat-5',
    title: 'Luxury Sandalwood & Shea Butter Body Lotion',
    slug: 'luxury-sandalwood-shea-butter-body-lotion',
    shortDescription: 'Deeply moisturizing 300ml body lotion scented with Mysore sandalwood.',
    description: 'Enriched with raw African shea butter and coconut oil. Non-greasy formula absorbs quickly to leave skin velvety smooth.',
    basePrice: 1999.00,
    salePrice: 1499.00,
    sku: 'SBJ-WELL-293',
    brand: 'PureVita',
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: true,
    rating: 4.8,
    reviews: 76,
    tags: ['body-lotion', 'sandalwood', 'skincare', 'shea-butter'],
    imageUrl: 'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?q=80&w=1000',
    stock: 50,
  },
  {
    id: 'prod-294',
    categoryId: 'cat-5',
    title: 'Organic Matcha Green Tea Powder (Ceremonial Grade)',
    slug: 'organic-matcha-green-tea-powder-ceremonial-grade',
    shortDescription: '100g tin of stone-ground Uji Japanese green tea powder.',
    description: 'Packed with L-theanine antioxidants for sustained calm energy without jitters. Vibrant emerald green color and smooth umami taste.',
    basePrice: 2999.00,
    salePrice: 2299.00,
    sku: 'SBJ-WELL-294',
    brand: 'PureVita',
    isFeatured: true,
    isNewArrival: true,
    isBestSeller: false,
    rating: 4.9,
    reviews: 38,
    tags: ['matcha', 'tea', 'superfood', 'gourmet'],
    imageUrl: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?q=80&w=1000',
    stock: 35,
  },
  {
    id: 'prod-295',
    categoryId: 'cat-5',
    title: 'Safety Razor & Sandalwood Shaving Cream Kit',
    slug: 'safety-razor-sandalwood-shaving-cream-kit',
    shortDescription: 'Double-edge brass safety razor with badger hair brush & 100g shaving tub.',
    description: 'Rediscover traditional barber grooming. Minimizes razor bumps and ingrown hairs while delivering an ultra-close shave.',
    basePrice: 3499.00,
    salePrice: 2699.00,
    sku: 'SBJ-WELL-295',
    brand: 'Aetheria Botanicals',
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: true,
    rating: 4.8,
    reviews: 49,
    tags: ['shaving', 'grooming', 'razor', 'menswear'],
    imageUrl: 'https://images.unsplash.com/photo-1621607512214-68297480165e?q=80&w=1000',
    stock: 30,
  },
  {
    id: 'prod-296',
    categoryId: 'cat-5',
    title: 'Handmade Cold-Process Herbal Soap Trio Set',
    slug: 'handmade-cold-process-herbal-soap-trio-set',
    shortDescription: '3x125g natural bar soaps (Neem & Tulsi, Turmeric & Honey, Charcoal).',
    description: 'Saponified coconut and olive oil soaps infused with pure botanicals. Free from SLS, parabens, and synthetic fragrance.',
    basePrice: 999.00,
    salePrice: 749.00,
    sku: 'SBJ-WELL-296',
    brand: 'Aetheria Botanicals',
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: true,
    rating: 4.7,
    reviews: 125,
    tags: ['soap', 'organic', 'herbal', 'skincare'],
    imageUrl: 'https://images.unsplash.com/photo-1607006482170-49633e9b1d97?q=80&w=1000',
    stock: 90,
  },
  {
    id: 'prod-297',
    categoryId: 'cat-5',
    title: 'Natural Silk Sleep Eye Mask with Cooling Gel',
    slug: 'natural-silk-sleep-eye-mask-with-cooling-gel',
    shortDescription: '100% 22-momme Mulberry silk blackout eye mask with removable gel insert.',
    description: 'Sleep soundly on flights or at home. Ultra-soft silk reduces eye area friction while gel insert calms puffy eyes.',
    basePrice: 1999.00,
    salePrice: 1499.00,
    sku: 'SBJ-WELL-297',
    brand: 'PureVita',
    isFeatured: false,
    isNewArrival: true,
    isBestSeller: false,
    rating: 4.8,
    reviews: 31,
    tags: ['eye-mask', 'silk', 'sleep', 'wellness'],
    imageUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?q=80&w=1000',
    stock: 45,
  },
  {
    id: 'prod-298',
    categoryId: 'cat-5',
    title: '100% Pure Organic Eucalyptus Essential Oil (30ml)',
    slug: '100-pure-organic-eucalyptus-essential-oil-30ml',
    shortDescription: 'Steam-distilled pure essential oil for aromatherapy & congestion relief.',
    description: 'Invigorate mind and clear sinuses. Add 3-5 drops to ultrasonic diffusers, warm steam baths, or carrier oils.',
    basePrice: 899.00,
    salePrice: 649.00,
    sku: 'SBJ-WELL-298',
    brand: 'Aetheria Botanicals',
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: true,
    rating: 4.7,
    reviews: 84,
    tags: ['essential-oil', 'eucalyptus', 'aromatherapy', 'wellness'],
    imageUrl: 'https://images.unsplash.com/photo-1608248597261-833258657640?q=80&w=1000',
    stock: 100,
  },
  {
    id: 'prod-299',
    categoryId: 'cat-5',
    title: 'Sprouted Raw Almond & Saffron Honey Spread (350g)',
    slug: 'sprouted-raw-almond-saffron-honey-spread-350g',
    shortDescription: 'Artisanal stone-ground nut butter made with raw organic wildflower honey.',
    description: 'Nutritious gourmet spread for breakfast toasts, smoothies, and fruit bowls. 100% natural without palm oil or refined sugar.',
    basePrice: 1499.00,
    salePrice: null,
    sku: 'SBJ-WELL-299',
    brand: 'PureVita',
    isFeatured: false,
    isNewArrival: true,
    isBestSeller: false,
    rating: 4.9,
    reviews: 27,
    tags: ['honey', 'gourmet', 'almond', 'superfood'],
    imageUrl: 'https://images.unsplash.com/photo-1587049352847-4a222e784d38?q=80&w=1000',
    stock: 40,
  },
  {
    id: 'prod-300',
    categoryId: 'cat-5',
    title: 'Natural Coconut Wax Massage Candle',
    slug: 'natural-coconut-wax-massage-candle',
    shortDescription: '200g low-melt temperature candle with warm jasmine & vanilla essential oils.',
    description: 'Melts into a warm, nourishing skin massage oil. Rich in Vitamin E and essential fatty acids for luxurious body treatments.',
    basePrice: 1799.00,
    salePrice: 1299.00,
    sku: 'SBJ-WELL-300',
    brand: 'Aetheria Botanicals',
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: false,
    rating: 4.6,
    reviews: 22,
    tags: ['massage-candle', 'spa', 'jasmine', 'body-care'],
    imageUrl: 'https://images.unsplash.com/photo-1603006905003-be475563bc59?q=80&w=1000',
    stock: 30,
  },
  {
    id: 'prod-301',
    categoryId: 'cat-5',
    title: 'Sun Protection Tinted Mineral Sunscreen SPF 50+',
    slug: 'sun-protection-tinted-mineral-sunscreen-spf-50',
    shortDescription: '100% Zinc Oxide reef-safe mineral sunscreen with sheer universal tint.',
    description: 'Broad-spectrum UVA/UVB protection without white cast. Matte finish suitable under makeup with 80-min water resistance.',
    basePrice: 1999.00,
    salePrice: 1499.00,
    sku: 'SBJ-WELL-301',
    brand: 'PureVita',
    isFeatured: false,
    isNewArrival: true,
    isBestSeller: true,
    rating: 4.8,
    reviews: 69,
    tags: ['sunscreen', 'spf50', 'mineral', 'skincare'],
    imageUrl: 'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?q=80&w=1000',
    stock: 65,
  },
  {
    id: 'prod-302',
    categoryId: 'cat-5',
    title: 'Peppermint & Cocoa Butter Lip Balm Trio',
    slug: 'peppermint-cocoa-butter-lip-balm-trio',
    shortDescription: '3x15g tin set of organic beeswax & cold-pressed coconut oil lip balms.',
    description: 'Heal chapped dry lips instantly. Long-lasting moisture seal enriched with natural Vitamin E and cooling peppermint oil.',
    basePrice: 799.00,
    salePrice: 599.00,
    sku: 'SBJ-WELL-302',
    brand: 'Aetheria Botanicals',
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: true,
    rating: 4.8,
    reviews: 140,
    tags: ['lip-balm', 'organic', 'skincare', 'basics'],
    imageUrl: 'https://images.unsplash.com/photo-1608248597261-833258657640?q=80&w=1000',
    stock: 110,
  },
  {
    id: 'prod-303',
    categoryId: 'cat-5',
    title: 'Artisanal Himalayan Pink Salt Scrub with Almond Oil',
    slug: 'artisanal-himalayan-pink-salt-scrub-with-almond-oil',
    shortDescription: '350g body polish scrub with coarse pink mineral salt & sweet almond oil.',
    description: 'Buff away dry flaky skin while infusing deep moisture. Leaves skin feeling silky smooth with delicate sweet almond aroma.',
    basePrice: 1699.00,
    salePrice: 1299.00,
    sku: 'SBJ-WELL-303',
    brand: 'PureVita',
    isFeatured: false,
    isNewArrival: true,
    isBestSeller: false,
    rating: 4.7,
    reviews: 41,
    tags: ['body-scrub', 'salt-scrub', 'himalayan', 'spa'],
    imageUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?q=80&w=1000',
    stock: 45,
  },
  {
    id: 'prod-304',
    categoryId: 'cat-5',
    title: 'Organic Kashmiri Saffron Threads (1g A++ Grade)',
    slug: 'organic-kashmiri-saffron-threads-1g-a-grade',
    shortDescription: 'Pure Mongra grade red saffron stigmas in airtight glass bottle.',
    description: 'Sourced directly from Pampore fields in Kashmir. Known for intense aroma, deep red color, and rich culinary/wellness benefits.',
    basePrice: 1299.00,
    salePrice: 999.00,
    sku: 'SBJ-WELL-304',
    brand: 'PureVita',
    isFeatured: true,
    isNewArrival: false,
    isBestSeller: true,
    rating: 4.9,
    reviews: 78,
    tags: ['saffron', 'kashmiri', 'gourmet', 'ayurveda'],
    imageUrl: 'https://images.unsplash.com/photo-1587049352847-4a222e784d38?q=80&w=1000',
    stock: 50,
  },
  {
    id: 'prod-305',
    categoryId: 'cat-5',
    title: 'Organic Hibiscus & Rose Wellness Herbal Tea',
    slug: 'organic-hibiscus-rose-wellness-herbal-tea',
    shortDescription: '150g caffeine-free ruby red herbal tea infusion with dried rose petals.',
    description: 'Rich in Vitamin C and antioxidants. Delicious hot or iced with a hint of honey for afternoon refreshment.',
    basePrice: 1199.00,
    salePrice: 899.00,
    sku: 'SBJ-WELL-305',
    brand: 'PureVita',
    isFeatured: false,
    isNewArrival: true,
    isBestSeller: false,
    rating: 4.8,
    reviews: 36,
    tags: ['herbal-tea', 'hibiscus', 'organic', 'gourmet'],
    imageUrl: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?q=80&w=1000',
    stock: 60,
  },
];

async function seed100Products() {
  const dbUrl = process.env.DATABASE_URL;
  const host = process.env.TIDB_HOST;
  const user = process.env.TIDB_USER;
  const password = process.env.TIDB_PASSWORD;
  const port = Number(process.env.TIDB_PORT || 4000);

  console.log('Connecting to TiDB Cloud for 100+ product catalog seed...');

  let connection: mysql.Connection;

  try {
    if (dbUrl) {
      connection = await mysql.createConnection({
        uri: dbUrl,
        ssl: { rejectUnauthorized: false },
        multipleStatements: true,
      });
    } else if (host && user && password) {
      connection = await mysql.createConnection({
        host,
        port,
        user,
        password,
        ssl: { rejectUnauthorized: false },
        multipleStatements: true,
      });
    } else {
      console.error('Error: Database configuration missing in .env.local');
      process.exit(1);
    }
  } catch (err) {
    console.error('Failed to connect to TiDB Cloud:', err);
    process.exit(1);
  }

  console.log('Connected to TiDB Cloud successfully.');

  // Select database
  await connection.query(`CREATE DATABASE IF NOT EXISTS shopping_by_jitesh; USE shopping_by_jitesh;`);

  // Count existing products
  const [existingRows] = await connection.query<mysql.RowDataPacket[]>(`SELECT COUNT(*) as count FROM products`);
  const initialProductCount = Number(existingRows[0]?.count || 0);
  console.log(`Current existing product count in database: ${initialProductCount}`);

  // 1. Ensure Categories Exist
  console.log('Upserting 5 main categories...');
  for (const cat of CATEGORIES_DATA) {
    await connection.query(
      `INSERT INTO categories (id, parent_id, name, slug, description, image_url, icon, is_featured, sort_order)
       VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
       ON DUPLICATE KEY UPDATE name=VALUES(name), description=VALUES(description), image_url=VALUES(image_url)`,
      [cat.id, cat.parentId, cat.name, cat.slug, cat.description, cat.imageUrl, cat.icon, cat.isFeatured, cat.sortOrder]
    );
  }

  // 2. Insert Products Idempotently
  let insertedCount = 0;
  let skippedCount = 0;

  console.log(`Starting idempotent insertion of ${PRODUCTS_DATA.length} products...`);

  for (const prod of PRODUCTS_DATA) {
    // Validate sale price <= base price
    if (prod.salePrice !== null && prod.salePrice > prod.basePrice) {
      console.warn(`[Price Error Skipped] Product '${prod.title}' salePrice > basePrice!`);
      continue;
    }

    // Check if SKU or Slug exists
    const [chkSku] = await connection.query<mysql.RowDataPacket[]>(
      `SELECT id FROM products WHERE sku = ? OR slug = ? OR id = ?`,
      [prod.sku, prod.slug, prod.id]
    );

    if (chkSku.length > 0) {
      // Product exists - update fields idempotently
      await connection.query(
        `UPDATE products
         SET category_id = ?, title = ?, short_description = ?, description = ?,
             base_price = ?, sale_price = ?, brand = ?, is_featured = ?,
             is_new_arrival = ?, is_best_seller = ?, is_active = TRUE,
             average_rating = ?, review_count = ?, tags = ?
         WHERE sku = ? OR slug = ? OR id = ?`,
        [
          prod.categoryId,
          prod.title,
          prod.shortDescription,
          prod.description,
          prod.basePrice,
          prod.salePrice,
          prod.brand,
          prod.isFeatured,
          prod.isNewArrival,
          prod.isBestSeller,
          prod.rating,
          prod.reviews,
          JSON.stringify(prod.tags),
          prod.sku,
          prod.slug,
          prod.id,
        ]
      );

      // Fetch actual product_id
      const actualProdId = String(chkSku[0].id);

      // Ensure Primary Image
      await connection.query(
        `INSERT INTO product_images (id, product_id, image_url, alt_text, is_primary, display_order)
         VALUES (?, ?, ?, ?, TRUE, 1)
         ON DUPLICATE KEY UPDATE image_url = VALUES(image_url)`,
        [`img-${actualProdId}`, actualProdId, prod.imageUrl, prod.title]
      );

      // Ensure Inventory
      await connection.query(
        `INSERT INTO inventory (id, product_id, quantity_available, quantity_reserved, low_stock_threshold)
         VALUES (?, ?, ?, 0, 5)
         ON DUPLICATE KEY UPDATE quantity_available = VALUES(quantity_available)`,
        [`inv-${actualProdId}`, actualProdId, prod.stock]
      );

      skippedCount++;
    } else {
      // Insert New Product
      await connection.query(
        `INSERT INTO products (id, category_id, title, slug, short_description, description, base_price, sale_price, sku, brand, is_featured, is_new_arrival, is_best_seller, is_active, average_rating, review_count, tags)
         VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, TRUE, ?, ?, ?)`,
        [
          prod.id,
          prod.categoryId,
          prod.title,
          prod.slug,
          prod.shortDescription,
          prod.description,
          prod.basePrice,
          prod.salePrice,
          prod.sku,
          prod.brand,
          prod.isFeatured,
          prod.isNewArrival,
          prod.isBestSeller,
          prod.rating,
          prod.reviews,
          JSON.stringify(prod.tags),
        ]
      );

      // Insert Primary Image
      await connection.query(
        `INSERT INTO product_images (id, product_id, image_url, alt_text, is_primary, display_order)
         VALUES (?, ?, ?, ?, TRUE, 1)`,
        [`img-${prod.id}`, prod.id, prod.imageUrl, prod.title]
      );

      // Insert Inventory Record
      await connection.query(
        `INSERT INTO inventory (id, product_id, quantity_available, quantity_reserved, low_stock_threshold)
         VALUES (?, ?, ?, 0, 5)`,
        [`inv-${prod.id}`, prod.id, prod.stock]
      );

      insertedCount++;
    }
  }

  // Verification Queries
  console.log('\n================ DATABASE VERIFICATION METRICS ================');

  const [totalProdRows] = await connection.query<mysql.RowDataPacket[]>(`SELECT COUNT(*) as count FROM products WHERE is_active = TRUE`);
  const finalTotalProducts = Number(totalProdRows[0]?.count || 0);

  const [catGroupRows] = await connection.query<mysql.RowDataPacket[]>(`
    SELECT c.name as category_name, c.slug as category_slug, COUNT(p.id) as product_count
    FROM categories c
    LEFT JOIN products p ON c.id = p.category_id AND p.is_active = TRUE
    GROUP BY c.id, c.name, c.slug
    ORDER BY c.sort_order ASC
  `);

  const [skuCountRows] = await connection.query<mysql.RowDataPacket[]>(`SELECT COUNT(DISTINCT sku) as count FROM products`);
  const uniqueSKUs = Number(skuCountRows[0]?.count || 0);

  const [slugCountRows] = await connection.query<mysql.RowDataPacket[]>(`SELECT COUNT(DISTINCT slug) as count FROM products`);
  const uniqueSlugs = Number(slugCountRows[0]?.count || 0);

  const [imgCountRows] = await connection.query<mysql.RowDataPacket[]>(`SELECT COUNT(DISTINCT product_id) as count FROM product_images`);
  const productsWithImages = Number(imgCountRows[0]?.count || 0);

  const [invCountRows] = await connection.query<mysql.RowDataPacket[]>(`SELECT COUNT(DISTINCT product_id) as count FROM inventory`);
  const productsWithInventory = Number(invCountRows[0]?.count || 0);

  const [invalidPriceRows] = await connection.query<mysql.RowDataPacket[]>(`SELECT COUNT(*) as count FROM products WHERE sale_price IS NOT NULL AND sale_price > base_price`);
  const invalidPriceCount = Number(invalidPriceRows[0]?.count || 0);

  console.log(`Initial Products: ${initialProductCount}`);
  console.log(`Newly Inserted: ${insertedCount}`);
  console.log(`Updated/Skipped Duplicates: ${skippedCount}`);
  console.log(`Total Active Products in Database: ${finalTotalProducts}`);
  console.log(`Unique SKUs: ${uniqueSKUs}`);
  console.log(`Unique Slugs: ${uniqueSlugs}`);
  console.log(`Products with Images: ${productsWithImages}`);
  console.log(`Products with Inventory: ${productsWithInventory}`);
  console.log(`Invalid Pricing Violations (sale > base): ${invalidPriceCount}`);

  console.log('\n--- Breakdown Per Category ---');
  for (const row of catGroupRows) {
    console.log(`- ${row.category_name} (${row.category_slug}): ${row.product_count} products`);
  }

  await connection.end();
  console.log('===============================================================\n');
}

seed100Products().catch((err) => {
  console.error('Fatal Seeding Script Error:', err);
  process.exit(1);
});
